### ISSUE TITLE
setting up FastField

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#10]
@briannakcalkins , @jenajordan , @jess-shue , I've added [this .md file](https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/Protocols/FastField%20setup.md) to document FastField setup. (Note: .md is similar to .Rmd, but a simpler version for GitHub that doesn't require knitting in R.)

I got the app on my phone, and it's working/ looking great. @briannakcalkins , it may be helpful for you to try it on a personal device before you have access to the lab iPads.

**Comment by teixeirak** [comment]
@jess-shue , I have two questions:
1- I may just be confused, but it seems the list of quads in Section 1 don't match available choices when you go to enter quad for specific trees
2- Should each person create their own FastField account? Or can we all share the lab account?

**Comment by teixeirak** [comment]
@briannakcalkins , I just discovered that there's a web app, so you can review there as you work on the protocol guide (#9 ).

**Comment by jess-shue** [comment]
@teixeirak 
1 - It looks like the form wasn't assigned the correct column from the data; it should show the quadrat numbers correctly now. 
2 - No, for now everyone should use the lab account (we are charged per user). The form should work for multiple people on the same account, but if it creates problems we can add users. We had used a lab account for our entire census without issue.

**Comment by teixeirak** [comment]
Thanks, @jess-shue !

**Comment by jenajordan** [comment]
I downloaded FastField app to my phone. No rush for me to log in - I still have plenty to learn here (even learning how to post a response here!). But it sounds like eventually @briannakcalkins & I will use the lab account log in.

**Comment by teixeirak** [comment]
@jess-shue , I think it would be valuable to add the surveyor name to the FastField form. We've been keeping track of that in all our previous censuses.

**Comment by teixeirak** [comment]
@jess-shue  & @ValentineHerr , we seem to have a problem with the data output into Fastfield, including nonsense lines that sometimes seem to break up individual records:

<img width="1618" alt="image" src="https://user-images.githubusercontent.com/6355854/120890101-b6752f00-c5ce-11eb-990e-1f5164b0aa92.png">

**Comment by teixeirak** [comment]
@ValentineHerr , would the above be messing up the checks?

**Comment by ValentineHerr** [comment]
Yes, probably.

**Comment by teixeirak** [comment]
@jess-shue , do you understand what's going on here?

@jenajordan, @briannakcalkins , @troger4, please disregard the error reports until we get this sorted out.

**Comment by ValentineHerr** [comment]
Actually, the only thing it will mess up is saying that the values that are moved to the empty line are missing from the original record (I assume the line above), even though they have been recorded. (my code first deletes the rows with empty quadrat).

**Comment by teixeirak** [comment]
This means it actually shouldn't have generated any erroneous reports, as we haven't yet coded any of the EAB tests. 

I wonder if those empty lines correspond to photos (???). It would be best to fix this in the app if @jess-shue knows how; otherwise I suppose we just need to shift filled cells in those lines up. I'd like to be sure we understand what causes it, though.

**Comment by jess-shue** [comment]
@teixeirak and @ValentineHerr 
Looking into this now, sorry for the delay. Just to clarify, the extra lines or misaligned rows were created when exporting all of the submissions from FastField Forms into a single Excel file, correct?
I just downloaded all 65 submissions as one file and checked tag 90715 but did not see that same issue as the data remains in separate worksheets within the workbook. An edit may be needed to the subform and the EAB/Chioanthus section as currently the tag numbers are not included there and that may be an issue when trying to connect the EAB specific data to the ash trees. Did you use R to combine the separate datasheets exported from FFF's to create the above file?

**Comment by teixeirak** [comment]
Thanks, @jess-shue . Yes, I believe he extra lines or misaligned rows were created when exporting all of the submissions from FastField Forms into a single Excel file, and that these were not manipulated by R. @ValentineHerr  can verify.

**Comment by ValentineHerr** [comment]
correct. [This excel file](https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/raw_data/FFF_excel/3e862d38-c202-4b35-977f-fedffb98710a.xlsx) was imply extracted from the zip file downloaded from FFF, (after selecting all the forms at once)

**Comment by jenajordan** [comment]
Question - is there any easy way in FF to, once a tree's data is entered, to have that tree identifier # removed from the list of remaining trees left in that quad? That would prevent the possibility of entering data twice for the same tree.

**Comment by jess-shue** [comment]
@jenajordan Sorry Jen, I've tried to explain this before but that is the biggest issue with FFF's - and albeit not a little one. It only sees the data we've given it in the static file and it does not recognize once you've entered data for a tree. With the newest version of the form you'll see 'Stem Count' field on the landing page. When you select the quadrat the stem count will show. As you enter data for stems, a number also appears on that main page next to 'Mortality'. The 'Stem Count' number and the 'Mortality' number should match to show you've collected all the stems. That doesn't prevent double entry, or eliminate the list for you, but it is a small check.

**Comment by jenajordan** [comment]
Okay. And I saw that stem count # - it is very helpful!

**Comment by jess-shue** [comment]
@teixeirak @ValentineHerr OK, there must be different ways to download the data - when I download all the files it exports an excel file with separate sheets and does not combine the EAB data onto one sheet with the other columns. The misaligned rows appear to be those from the extra data recorded for ash trees.
Downloading the data with separate sheets would eliminate the row error, but we then need to compile the sheets into one file. Let me see if I can figure this out in R!

**Comment by teixeirak** [comment]
@jess-shue , maybe wait until @ValentineHerr gets a chance to respond on this, as the R code would need to be worked into her system. It may be more efficient for her to write it.

**Comment by jess-shue** [comment]
@teixeirak OK, I'll hold off for now. Do you want me to send the file I downloaded from FastField Forms? I'm not 100% sure why we're seeing different formatting.
I think part of the problem is caused by the 'section_2' worksheet that contains the extra ash data. I'm going to edit the form to include the tag and stem tag of the tree automatically. This won't correct the data collected in the field so far, but will help combine the worksheets going forward.

**Comment by ValentineHerr** [comment]
@jess-shue, sorry for the delayed response here.

> Downloading the data with separate sheets would eliminate the row error, but we then need to compile the sheets into one file.

I am not a huge fan of downloading each sheet separately as it is a lot more steps, but if that avoids those misaligned rows, maybe it is worth it.

If I understand well, it sounds like you need to update FFF so that the 'section_2" also contains the tags so the merging is easy?
If yes and if you happen to redownload the data while you figure that out, yes, it would be great if you can put it in the raw_data/FFF_excel folder. If not, I'll go and download them myself, just let me know.

It is easy to work any existing script into the continuous integration system, so if you had worked on a way to merge the sheet together it would have been fine. But I don't mind working on a script once new format is in.

**Comment by jess-shue** [comment]
@ValentineHerr No, I didn't download each file individually but as one workbook with separate sheets. When you downloaded the data from FFF's, did it create an excel workbook with multiple sheets? 
From the screenshot shared above all of the data are on one sheet with misaligned rows for the EAB data columns. This is not what I receive when downloading and why I asked if it had been post-processed somehow in R. I am able to download one file of all of the submissions, but they include separate sheets:  Root, Form Meta Data, multiphoto_picker1, section_1, section_2, and subform_1

**Comment by ValentineHerr** [comment]
Oh ok,! Let me try to download again and see if I get something different than last time.

**Comment by ValentineHerr** [comment]
I am getting the same file...

@jess-shue,  do you have this interface when ready to download?

![image](https://user-images.githubusercontent.com/19673377/122094754-80a82580-cdda-11eb-968e-50322f289a16.png)

 I click on Excel (tried CSV and it does not give what we need) .

**Comment by jess-shue** [comment]
@ValentineHerr OK, it looks like the new version of the website is causing the problem. I still have access to what they call the 'Legacy Portal'. Using that version of the website, I can download an excel file that I've added to the raw_data/FFF_excel folder.

CSV does not export all of the data. The issue becomes connecting the EAB data to the correct row when combining the sheets into one file.

**Comment by ValentineHerr** [comment]
thanks for uploading the data @jess-shue.

 Here is what I see/think:
 - section_1 has 1737 rows and section_2 has 1738 --> no one-to-on relationship
 - section_2  Tag and StemTag are empty --> no easy match up.
 - if any intern or myself proceeds to the download, we will have the other forms with misaligned data
 
So maybe it is easier to just re-align the data, assuming the misaligned line belongs to the previous line.

**Comment by jess-shue** [comment]
@ValentineHerr the Submission ID and row of the data match for the two sections from a quick assessment. 
- I can combine sheets in R, but I don't know how to designate that the submission ID and row of section_1 should align with the same from section_2
- Going forward, new submissions will have the Tag and StemTag filled in and will make this much easier to match the data.
- Certainly can align the data assuming that is correct and check!

**Comment by ValentineHerr** [comment]
> @ValentineHerr the Submission ID and row of the data match for the two sections from a quick assessment.

It does until row 1722 where there is one extra row from submission 5e8cb8c4-be05-4b6c-9296-a745e7224723 in section_2 than in section_1.

If they were aligning exactly, we would just need `cbind` to put the data together.

**Comment by jess-shue** [comment]
@ValentineHerr Ah, so close! In your script can we remove that extra line and then cbind the data? This would not impact the raw data but allow us to move forward, correct? There are no EAB data after that row either and all those columns should be blank for the remaining rows/trees.

**Comment by ValentineHerr** [comment]
Actually, it does not work...
Look at row 1673 in section_2. It should be from a fram since there is data in there.



![image](https://user-images.githubusercontent.com/19673377/122101493-5d817400-cde2-11eb-81f3-0024790ab8d8.png)

But then row 1673 in section_1 is a litu, the fram is right above on row 1672.

![image](https://user-images.githubusercontent.com/19673377/122101595-7f7af680-cde2-11eb-948b-97c653118a70.png)



Who is going to be downloading the forms in the future (@teixeirak)? if not you @jess-shue and your 'Legacy Portal' we might be better off finding a solution for the other format (the one with misaligned info), which, I think I now trust better as, for the same tree mentioned above, the data is on next row:

![image](https://user-images.githubusercontent.com/19673377/122101894-d680cb80-cde2-11eb-8e1f-9de065d97acf.png)

**Comment by teixeirak** [comment]
> Who is going to be downloading the forms in the future (@teixeirak)?

I'd like the interns to download/ push to GitHub after each day's work.

**Comment by jess-shue** [comment]
@teixeirak and @ValentineHerr Update from FFF's:  I reached out to FastField Forms about the data exporting/formatting issue and they are still working on fixing some bugs with the new portal's processing. When you login to the FFF's account, do you see these menu options on the left? The "Legacy Portal" would export the data into separate sheets that would then need to be consolidated. Without the tree tags in the ash section to start, this would still be a problem, but if there are issues with exporting from the new portal this is the other option.
![image](https://user-images.githubusercontent.com/37407801/122794530-5945d280-d28a-11eb-932e-8b4fd114194d.png)

**Comment by teixeirak** [comment]
Yes, I see the legacy portal.

We can use this to get a file in the needed format, correct? It would be good to get at least a temporary solution here because the field team is making rapid progress, and we want to be able to check those records sooner rather than later.

**Comment by jess-shue** [comment]
@teixeirak This at least provides the data in separate sheets - the main issue will be linking the ash data to the specific stem. @ValentineHerr took a look at a spreadsheet I had downloaded previously, so she can comment on aligning the data from multiple sheets as it may not work as I had thought - with the submissionID and row of the data matching.

Has everyone updated their iPads to be on the latest version of the form? It appears submissions are still on version 10 and the tag/stemtag are not populating for the ash section. Everyone should update their form to be on version 11 so new submissions will include those tag/stemtag numbers to help merge the multiple sheets appropriately.

**Comment by teixeirak** [comment]
> Has everyone updated their iPads to be on the latest version of the form? It appears submissions are still on version 10 and the tag/stemtag are not populating for the ash section. Everyone should update their form to be on version 11 so new submissions will include those tag/stemtag numbers to help merge the multiple sheets appropriately.

@briannakcalkins , @jenajordan , could you please make sure the iPads are updated with the latest version of the FastField form?

**Comment by teixeirak** [comment]
> @teixeirak This at least provides the data in separate sheets - the main issue will be linking the ash data to the specific stem. @ValentineHerr took a look at a spreadsheet I had downloaded previously, so she can comment on aligning the data from multiple sheets as it may not work as I had thought - with the submissionID and row of the data matching.

@ValentineHerr , could you please update me on where we are with this? (I'm sorry, I'm confused as to what's the next step here...)

**Comment by ValentineHerr** [comment]
Sorry I wasn't able to work on this sooner.

I ended up correcting the misalignment from the bulk Excel import, where all the data comes into one excel file and is located in only one tab.

I updated everything with [this commit](https://github.com/SCBI-ForestGEO/SCBImortality/commit/19e7943598b1eef362d3bc8328a21ab26bc7eb0c). 

I think it worked but tests failed and I need to figure out why the % complete did not change.

So this is the[ protocol to download the data](https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/Protocols/FastField%20Download%20forms.md).

**Comment by teixeirak** [comment]
Thanks @ValentineHerr!  From what I see,  % complete updated (34%).

**Comment by ValentineHerr** [comment]
Oh right, great! it took a few minutes to show up for me.

**Comment by teixeirak** [comment]
I think we can close this, then? I'll start a new issue for putting this to routine use.

**Comment by ValentineHerr** [comment]
Yes, I think we can close.
