### ISSUE TITLE
photo fix census errors

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#100]
There are a number of errors that we should be able to fix by consulting photos (see issue #97).

If submissions are downloaded as a pdf, the images should be embedded in the document. It might have to be two separate files due to limits on pdf sizes. 

![Fastfields submissions](https://user-images.githubusercontent.com/47282393/202055598-19db8eff-5d51-4cc9-a07f-8585b4882102.JPG)

_Originally posted by @mageeluke in https://github.com/SCBI-ForestGEO/SCBImortality/issues/97#issuecomment-1316097403_

**Comment by teixeirak** [comment]
Note that this are classified as auto_fix errors (name inappropriate, but classified this way because they are not field fix).

**Comment by teixeirak** [comment]
@mageeluke or @djj4tree , what's your process for editing data in FastField forms from the office?

**Comment by djj4tree** [comment]
We would dispatch the form and correct the error and then submit the corrected form

**Comment by teixeirak** [comment]
Thanks @djj4tree ! 

For the record here, the easiest way to dispatch would be through the legacy portal, accessible here: https://portal.fastfieldforms.com/SubmissionActivity. Instructions are here: https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/doc/Protocols/editing%20records%20with%20errors.md
