### ISSUE TITLE
clean up field fixes

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#104]
@ValentineHerr , I just pushed the latest round of field fixes from Katherina. She believes that she has got all the fixes possible without leaves on the trees. The remainder should be dealt with by code as follows:

#### `% crown intact` > `% crown living`  (n=10): 
- if dead standing, keep `% crown intact` and change `% crown living` to 0 (n=1).
- if alive, and if `% crown living` - `% crown intact`<5, apply the `% crown intact` to both fields (n=3)
- for the remainder (n=6), trees are "A" status with `% crown intact` <10 and `% crown living` ≥95. These most likely have a typo in `% crown intact`. Please set these to 'NA'

#### missing stems (n=34): 
- Katherina reports that she found a few of these that looked alive, but she didn't feel confident making that call in the winter (no leaves). The decision is that we can't assess these now, so status of all should be set as dead not found (DN)

#### status_AU_DS_or_DC_but_no_FAD
- stem 92360 has note "Crushed by 92362". FAD should be "CR"
- there are 3 with "M" status in 2021. Is this a code for missing?
- Katherina said that she couldn't find the remainder of these (n=2). Code as "U" (unable to determine cause of death).

**Comment by ValentineHerr** [comment]
> * if alive, and if `% crown living` - `% crown intact`<5, apply the `% crown intact` to both fields (n=3)

The only thing with that is that they will now show up as "missing_percent_crownt_intact".

**Comment by teixeirak** [comment]
True. Let's let those 3 errors stand for now, and we can try to grab that info next time someone goes to the plot.

**Comment by teixeirak** [comment]
Could you please post the tag numbers here? Maybe Katherina can grab them next week.

**Comment by teixeirak** [comment]
> Could you please post the tag numbers here? Maybe Katherina can grab them next week.

These are the tags: 

12474
22186
22522
131325
162589
182213

**Comment by ValentineHerr** [comment]
Sorry I misunderstood what this meant.  Which makes me realize the CI didn't work after my last fix. I'll work on that.

**Comment by teixeirak** [comment]
@KatherinaWilkins is now on GitHub! I'm flagging her here, as this would be a good place to report the missing crown positions (or email me or Valentine).

**Comment by teixeirak** [comment]
@ValentineHerr , this is ready to fix with the info in the last commit.

**Comment by ValentineHerr** [comment]
also crown living is not > crown intact for 22522 and 182213

**Comment by teixeirak** [comment]
Pasting here for reference:

<img width="541" alt="image" src="https://user-images.githubusercontent.com/6355854/224369077-1c4d7307-a7a2-4c4a-85b3-d558f423a102.png">

**Comment by teixeirak** [comment]
> 131325 is empty in that file, is that normal?

@KatherinaWilkins or @jenajordan , perhaps you know what's going on here? (Cell highlighted yellow in image above)

**Comment by teixeirak** [comment]
> also crown living is not > crown intact for 22522 and 182213

@ValentineHerr , for these 2 (highlighted blue), please apply this rule:

> * if alive, and if `% crown living` - `% crown intact`<5, apply the `% crown intact` to both fields

**Comment by teixeirak** [comment]
I think this is done.
