### ISSUE TITLE
drop <10cm Fraxinus

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#109]
We have decided to drop the small (<10cm) *Fraxinus*, which were included to capture the effects of EAB across the full size range. Motivation: 

(1) Most as susceptible to EAB have already been killed. Most of the remaining ash (small) show no sign of EAB
(2) These take a lot of time to census.

@jess-shue , could you please update the app to remove these? 

(Also flagging @rmh24.)

**Comment by jess-shue** [comment]
@teixeirak @rmh24 
I'll need to know when no one will be in the field/editing the app. Please give me a day when I can edit - Monday would work particularly well as I have two new Technicians starting Tuesday and will be training them the rest of the week.

**Comment by teixeirak** [comment]
Actually, today would be great if at all possible, as no one is in the field. Rachel is likely to be in the field on Monday, although her plans are uncertain right now. If today is not possible, we can keep you updated about Monday.

**Comment by jess-shue** [comment]
@teixeirak I'm supposed to be in the field conducting SERC's census. I will try to do it quickly, but if not, it will have to wait.

**Comment by teixeirak** [comment]
If it doesn't work to do it quickly now, I think it's okay to wait until a more convenient day. In the meantime, we can just skip them knowing that the change is coming.

**Comment by jess-shue** [comment]
@teixeirak Can I also remove the CHVI? I can set a filter to only include stems that are at least 100 mm. This would exclude anything less than that, which should only be CHVI and FRAM.

**Comment by teixeirak** [comment]
Yes, please remove CHVI / all stems under 100mm

**Comment by jess-shue** [comment]
Done.
