### ISSUE TITLE
define system for processing FastField forms + photos

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#11]
@ValentineHerr , we need to come up with a system for saving the FastField files.

My understanding is:
- FastField creates Excel files (Jess sent us an example). There will be many-- one per quadrat.
- we'll want an R script to extract the sheet of interest/ manipulate as needed/ compile into single sheet.

Questions:
- @jess-shue , what's the process for retrieving the files? I'm wondering if someone will need to go in manually and move them to GitHub, or if they could automatically be saved to a folder in GitHub (although someone would still need to push them)
- @ValentineHerr , what do you see as the best way to handle these? Perhaps save in a separate folder, or sub-folder in raw data? I suppose we just count these as raw data, right? (So no raw data .csvs, just .xlsx.)

**Comment by ValentineHerr** [comment]
Yes @teixeirak, I think that if the output of FastField is one .xlsx file per quadrat, we can create a sub folder within raw_data for all the 2021 census .xlsx files. Then we can have a script (that could run automatically when something is added in the subfolder) that pulls the right sheets together into a .csv file saved in the main raw_data folder. That main .csv file could then be used for the checks.

**Comment by jess-shue** [comment]
Hi @teixeirak  and @ValentineHerr , FastField has a few options for file delivery. You can download files manually, or you can have them directly emailed, or sent to Dropbox. One of you will need to go into the account to set this up as you have to allow Dropbox to authorize the setup of a folder. I can help walk you through this, and there are other options that may be of interest:
![image](https://user-images.githubusercontent.com/37407801/119829465-42010880-bec9-11eb-82f1-5617ce7542d9.png)

**Comment by ValentineHerr** [comment]
Thanks @jess-shue, this is helpful. I wonder if there would be a way to directly push the file to GitHub rather that e.g. Dropbox... Maybe the HTTP/HTTPS option? Have you ever tried it? I looked online but I found little help.
Maybe the easiest will be Dropbox but that Dropbox owner will have to make sure to push to GitHub.

**Comment by jess-shue** [comment]
@ValentineHerr  I have not tried HTTP/HTTPS, but we could give it a test run and see...

**Comment by jess-shue** [comment]
@teixeirak @ValentineHerr I attempted to add the delivery option to a URL in FastField Forms. I created a FFF_test folder in the raw_data folder. After submitting a quadrat of data, it has not shown in the folder. I've sent a help ticket to FFF's for assistance as there may be something I'm missing.

**Comment by jess-shue** [comment]
@teixeirak @ValentineHerr Response from FFF's:  "When delivering the data with the HTTP/HTTPS action the endpoint you are delivering to will need to be setup to accept a restful POST of data. This will usually need to be a custom endpoint, and not a regular website."
Does this make sense to either of you?

**Comment by ValentineHerr** [comment]
Thank you so much for trying this out @jess-shue! I am not familiar with this but will look into it and will get back to you if I can figure something out.

**Comment by ValentineHerr** [comment]
Well, @jess-shue, I am out of my league... very not familiar with this stuff... tagging @rudeboybert, who might be able to help.

@rudeboybert, are you familiar with setup GitHub repos to accept a restful POST of data? We want FastFieldForm to automatically create a file in this repo (when someone is done with the mortality census of a quadrat and submits the form).

If not, my next idea would be to have the data be sent to the lab's Google Drive. Then I may be able to write a workflow that would automatically pull the data from there and push it to GitHub... but I think I'd need to set up a GitHub secret to store the cache that would says the lab's  Google drive allows access to GitHub... This is also something I am not familiar with....
But if I can't figure that out, we will at least have the data in the lab's google drive and someone can go fetch it there and put it on GitHub manually...
@teixeirak, what do you think?

**Comment by teixeirak** [comment]
Where are you with this now? Based on notifications from the lab gmail account, it seems you made some progress.

**Comment by teixeirak** [comment]
@ValentineHerr , we now have some data files available in FastField (login info [here](https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/Protocols/FastField%20setup.md)). My first attempt to download didn't get it right, but you can access it if you're ready to work on it before @jess-shue or I get it loaded on GitHub.

**Comment by ValentineHerr** [comment]
Ok, I downloaded all forms at once, they come into one Excel file. 
I added [this first draft of a .md file](https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/Protocols/FastField%20Download%20forms.md) that I'll edit when I understand better how to handle the future forms.
I think (but maybe @jess-shue knows better) that it might be best to download all forms ever filled at once, just in case some older ones get edited in FFF. That would mean we should always overwrite the previous excel file.

**Comment by ValentineHerr** [comment]
Can I delete the form that you submitted on may 25, @jess-shue ? I am assuming it was a test?

![image](https://user-images.githubusercontent.com/19673377/120682005-f8389500-c469-11eb-82e1-705849d19815.png)

**Comment by jess-shue** [comment]
@ValentineHerr  Yes! Feel free to delete that file as it was just a test.

**Comment by ValentineHerr** [comment]
I think we can close this
