### ISSUE TITLE
rules for fixing % crown living > % crown intact

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#13]
We have one check to test that `percentage of crown living` ≤ `percentage of crown intact`. 

I think this may be fixable with code if people consistently tend to make the same type of error. I see two possible types:
1- estimates are taken independently, and percentage crown living overestimated (fix: if `percentage of crown living` > `percentage of crown intact`, set `percentage of crown living_corrected` = `percentage of crown intact`)
2- estimates % living for only the intact crown (correction:`percentage of crown living_corrected` = `percentage of crown intact` *`percentage of crown living_reported`) 

@briannakcalkins , @jenajordan , @troger4, @jess-shue , what do you feel would be the more common type of error? @ValentineHerr , we can also pay attention to what error tends to be made.

I think my personal tendency would be error type 2, but maybe others are different? (In which case this can't be automatically fixed.)

**Comment by jenajordan** [comment]
Clarification on measuring these 2...

#1: first, estimate % crown intact (this is the portion of woody material in crown remaining, yes?)

#2: next, estimate % of crown living (this is the portion of green leaf material in crown remaining, yes? I think my errors have been that I was measuring % of #1 that was living.)

(it might just be me - calling it  "% woody crown intact" and "% green crown intact (or living)" would be clearer. That is, if I'm on the right track. That said, I hope to get it straight going forward.

**Comment by teixeirak** [comment]
@jenajordan , You've got it right. I don't know that you've made any errors.... just seeing what you think the tendency would be. Sounds like your tendency for error would be the same as mine. If everyone agrees that if they get % crown living > % crown intact, it would be because we were measuring % of the part of the crown that's intact, we can probably correct these cases as `percentage of crown living_corrected` = `percentage of crown intact` *`percentage of crown living_reported`

**Comment by ValentineHerr** [comment]
Does this need to be fixed by the code? if yes, should it be applied to all stems up until the date of this issue?

**Comment by teixeirak** [comment]
let's have this be a field--or at least manual--fix for now.

**Comment by teixeirak** [comment]
I'm going to close this. We can reopen later if we decide this could be fixed automatically.
