### ISSUE TITLE
using continuous integration system

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#15]
@briannakcalkins , @jenajordan , @trogers4, 

We now have a fully working continuous integration system! (Big thanks to @ValentineHerr  , @jess-shue, and @rudeboybert!)

We'll still probably want to do some cleanup to make the process smoother/ easier to understand. It's now time to put this to routine use. The instructions for pushing your newly collected data so that it gets checked are here: https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/Protocols/FastField%20Download%20forms.md.

We also have an update on census progress: 34% complete. You're making great progress!

**Comment by teixeirak** [comment]
Test results are here: https://github.com/SCBI-ForestGEO/SCBImortality/tree/main/testthat. They're not super user-friendly yet, but hopefully functional.

@ValentineHerr and @rudeboybert , we'll want to have some system for tracking the issues that have been caught and fixed, hopefully before our awesome, fast field team starts fixing them!

**Comment by ValentineHerr** [comment]
My immediate solution would be to append the reports to ongoing files that don't get deleted when the issues are fixed.

I'll start working in this now.
Let me know if there is a specific place where would want these files to be, otherwise I'll create a new folder in the reports folder.

**Comment by ValentineHerr** [comment]
OK, now [this folder](https://github.com/SCBI-ForestGEO/SCBImortality/tree/main/testthat/reports/trace_of_reports), will be the one where the reports don't gets erased when the issues are solved. So at the end of the census, we can compare the "clean data" with these files.

**Comment by teixeirak** [comment]
that's great; thanks!

**Comment by jenajordan** [comment]
Teagan, Bri, & I will be at the plot tomorrow - I'll get my 1st attempt at pushing the data.
