### ISSUE TITLE
Fix issues by code when possible

### ISSUE THREAD

**Issue by ValentineHerr** [SCBI-ForestGEO/SCBImortality#16]
Reports are now separated into 2 groups, the issues that need to be fixed by going back to the field and the ones that can be fixed by the code.
I need to write the code that fixes the second ones.

**Comment by teixeirak** [comment]
Have you pushed that change? I don't see it yet.

**Comment by ValentineHerr** [comment]
hmm... it has messed up things... for some reason the transition is not easy...
