### ISSUE TITLE
add field for data collector to FastField

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#17]
@jess-shue , could you please add a field for data collector? As I'm thinking about @rudeboybert 's paper, I think it would be really useful to have this data (to track learning in surveyors). It would also may be helpful to separate out errors by surveyor  so that everyone can know what they're getting wrong.  It would be helpful if we could do this ASAP.

**Comment by teixeirak** [comment]
Note: we should include this for Harvard Forest as well.

**Comment by jess-shue** [comment]
@teixeirak There is a 'Personnel' field in the SCBI Mortality form already. It was added more recently so the initial files will not have it. I'll get a list of personnel from Dan and include it for HF.

**Comment by teixeirak** [comment]
Wonderful! Thank you!
