### ISSUE TITLE
set up continuous updates of mortality figure

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#19]
I'd like to set up updating of [this figure](ttps://github.com/SCBI-ForestGEO/SCBImortality/blob/main/R_results/Barplots_MortalityRates_and_BiomassMortality2020.tiff) as part of the continuous integration system, and then to show it on the front page of the the repo, something like this:

![image](https://user-images.githubusercontent.com/6355854/124180637-76e11c00-da82-11eb-9555-4970d4b53208.png)

This is an intended figure in @rudeboybert's paper. More broadly, the goal is to be able to detect when a species has an unusual mortality rate before we finish the census.

@briannakcalkins , I wonder if you'd be up for taking a stab at this? (asking @ValentineHerr for help as needed) We already have the code to produce the current figure. It should be fairly straightforward, right @ValentineHerr ? (or are there issues I'm not aware of?)

**Comment by ValentineHerr** [comment]
I haven't looked at that code for a while but it probably requires a bit of work to merge the new trees to the previous census and allow stems to not be accounted for (since the current census is not finished). It should be feasible though.

**Comment by teixeirak** [comment]
@ValentineHerr , this is great; thank you! Is this updated as part of the CI?

(And wow.... oak mortality keeps rising!)
