### ISSUE TITLE
code tests for continuous integration

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#2]
@ValentineHerr , I'm starting a running list of tests that I think would be valuable:

- [x] for each quadrat censused, all expected trees were censused. *This should not cause the batch data upload to fail, but it should generate a warning with a list of trees that were missed.* 
- [x] Related to the above, it would be good to program a test for entire census completion: census doesn't pass test of completion until all trees have been censused. It would be useful to have a continuously updated status in terms of % stems censused. 
- For any unhealthy or dead tree, all required info was recorded (need to come up with list)
- For each live tree, required info was recorded
-  some consistency checks among fields: e.g., if stem rot is recorded, it's severity level should be recorded.

See [this file for list](https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/testthat/list%20of%20tests.md)

**Comment by ValentineHerr** [comment]
Working on this using mort20 as guinea pig for now. 
Looking at the set of trees that should have been censused according to 3rd main census, it looks like some Fraxinus were missed fram (65), frpe (1) and frsp (1)... they are also missing from mort19. They are on the smaller side.

I'll leave the check fail for now.

**Comment by teixeirak** [comment]
This test will be quite useful!

**Comment by ValentineHerr** [comment]
Ok I worked on the 2 first items in the list:
- Files with subset of data that fail the test can be found [here](https://github.com/SCBI-ForestGEO/SCBImortality/tree/main/testthat/reports), (which is where the button that says check status in the README file sends)
- The main readme file on main page of repo show the % completion

 I'll work on the rest when we have the forms ready.

**Comment by teixeirak** [comment]
This is great; thanks! 

Of course, we'll want to create a system to archive reports by year and switch over the tests to the 2021 census.

**Comment by ValentineHerr** [comment]
I was thinking that we don't need to archive the reports, as they should be empty once all the issues have been resolved and the census has been closed. 
2020 is an exception as some stems were missed and the census was closed before that was addressed.
I have not checked the previous censuses as the test is set up to look at the latest one.

**Comment by teixeirak** [comment]
Right, I don't see any need to archive the reports. 

We don't want to apply this system to 2020, although it would be valuable to retrospectively run checks on prior censuses (lower priority).

**Comment by teixeirak** [comment]
@ValentineHerr , I’m getting this notice after every time I push to the repo (e.g., protocol documents). I’m just ignoring, but eventually if there’s a way to limit the tests to pushes that include data, that would be helpful.

<img width="630" alt="image" src="https://user-images.githubusercontent.com/6355854/119570610-57b5e700-bd7e-11eb-917b-c603398a250f.png">

**Comment by ValentineHerr** [comment]
Yes, I was thinking about fixing that. I need to find out how to run the test only when the raw data folder is edited. Will work on it tomorrow.

**Comment by ValentineHerr** [comment]
Ok @teixeirak, I think I fix that. Now the workflow will be triggered only when a change is made in the raw_data folder (not its README.md file).
I tested it and it worked for me but let me know if you still get emails when you push things in other folders.

**Comment by teixeirak** [comment]
Seems to be solved; thanks!

**Comment by teixeirak** [comment]
@ValentineHerr , I've started a list of checks to set up [here](https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/testthat/list%20of%20tests.md) (at this point just transferring the items at the top of this issue).

**Comment by teixeirak** [comment]
@briannakcalkins (or @jenajordan ), you can edit the file referenced above if you think of tests that should be included. I'm going to add a few more examples, and then add specific tests that I think of, but it would be great if you could add tests that seem relevant as you work with the protocol.  As I mentioned yesterday, we'll set up a session with @rudeboybert to orient you to the continuous integration setup sometime next week, I think.

To edit, simply hit the pencil icon in the upper right corner, and copy the .md table formatting to add rows.

**Comment by jenajordan** [comment]
@teixeirak & @briannakcalkins - do checks we've discussed before (i.e. percent crown is 100% or less) go here, or have these already been incorporated)?

**Comment by teixeirak** [comment]
I believe that @jess-shue has constrained numerical values (e.g., percents) to possible values. I ended up adding quite a few more tests, so you can see examples of what I have in mind. These are tests that are difficult or impossible to constrain inn FastField, but important for ensuring census completion and consistency. I'll stop on this for now. One subject I haven't touched yet is the EAB census add-on.

**Comment by ValentineHerr** [comment]
@teixeirak, thanks for the list of tests.md file, this is very helpful.
I don't think I can code those tests yet without having a template of the mort_2021.csv  file (which, i understand will be a little different than 2020). But the coding should be very fast so I can work on it at the first upload or, alternatively, when Jess is done generating the form, we can fake the completion of a few trees and I can use that to test the code.

**Comment by jess-shue** [comment]
@teixeirak , @ValentineHerr  the form is fairly close to finished at this point. One clarification:  do you want to record the same extra fields for Chioanthus as you do for all of the ash trees? I can have the app show the extra section for both species; currently it only shows that section if it is an ash.

**Comment by teixeirak** [comment]
> do you want to record the same extra fields for Chioanthus as you do for all of the ash trees?

Good question, @jess-shue . I'm actually not sure if Chioanthus would show the same symptoms of EAB as ash. Let's go ahead and include it.

**Comment by teixeirak** [comment]
Regarding a sample file for @ValentineHerr  to work with.... Perhaps @briannakcalkins or @jenajordan could go in and generate some fake data using the form. We'll want to be sure to get at least one ash and one dead tree. Valentine could start with that, and once we get out in the field she can try the tests on real data. (She could also just code it after our first day in the field, but having a fake form would help to get the whole system running smoothly.)

Here is the link to the form: https://manage.fastfieldforms.com/WebForm/164481/Form/639377.

**Comment by ValentineHerr** [comment]
@teixeirak, FYI, I updated the workflow so that it looks at the FFF forms directly. Working on adding more tests now, but there is already some things to check/fix in the [reports forlder](https://github.com/SCBI-ForestGEO/SCBImortality/tree/main/testthat/reports)

**Comment by teixeirak** [comment]
Thanks! This is great.

**Comment by ValentineHerr** [comment]
@teixeirak, in your list of test you say " DWR (dead with resprouts) not selected", where would that be entered? in the status? (can't find it in protocole nor form)

**Comment by ValentineHerr** [comment]
never mind! I just missed it.

**Comment by ValentineHerr** [comment]
@teixeirak, where do I find the key for the letters in FAD? the one I see ([here](https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/Protocols/figures_tables/FAD%20table.png)) does not have `wound`, e.g.

**Comment by ValentineHerr** [comment]
@jess-shue, how do I link a tree to its photo in the excel file?

**Comment by teixeirak** [comment]
@ValentineHerr , here's the [latest protocol version of our protocol](https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/Protocols/Mortality-Protocol-2021.pdf), which @briannakcalkins  is working on. And Dan's is [here](https://github.com/SCBI-ForestGEO/SCBImortality/tree/main/Protocols/Reference). Does that get what you need?

**Comment by ValentineHerr** [comment]
> @ValentineHerr , here's the [latest protocol version of our protocol](https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/Protocols/Mortality-Protocol-2021.pdf), which @briannakcalkins is working on. And Dan's is [here](https://github.com/SCBI-ForestGEO/SCBImortality/tree/main/Protocols/Reference). Does that get what you need?

Ok, yes, it is in Dan's protocol, @briannakcalkins, I think you need to add "W = Wound" in the FAD table of the current protocol (and check that no other codes are missing).

**Comment by teixeirak** [comment]
@ValentineHerr , as discussed in lab meeting, we'll want to 
(1) classify reports into those that require field checking versus those that can be fixed by code
(2) have the code automatically fix those that can be fixed by code, while saving a record of what has received this fix
(3) also save a record of what has had to be corrected in the field

**Comment by teixeirak** [comment]
Oops, didn't mean to close this!

**Comment by teixeirak** [comment]
@ValentineHerr , my comment in the latest commit shows an example of when we need to either perform tests in a certain order or modify some tests. There may be others. The tests are all independent, correct? So I assume it's better to modify the tests than to rely on a certain order (with fixes)?

**Comment by jess-shue** [comment]
> @jess-shue, how do I link a tree to its photo in the excel file?

@ValentineHerr This is the first time I'm using the photos option in the app and it does not present a clear connection between the stem and the images. There is a 'Comment' column that exports into the excel file with the link to the photo in the 'Photo' column. We may need to type the tag number into the 'notes' on the app for a quick fix to this issue...

**Comment by ValentineHerr** [comment]
Ok, now the reports should be separated into 2 types, and the CI works again.

**Comment by teixeirak** [comment]
Hmmm, I still don't see the 2 groups...

**Comment by ValentineHerr** [comment]
Make sure you refresh, I should be there:

![image](https://user-images.githubusercontent.com/19673377/122994397-6b04a400-d376-11eb-9f0e-2477f6ef825b.png)

**Comment by teixeirak** [comment]
So strange! Here's what I see (just refreshed): 
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/6355854/122994913-e9614600-d376-11eb-96e9-814d3744ae04.png">

**Comment by teixeirak** [comment]
oh, sorry, nevermind! I'm not in reports folder.

**Comment by ValentineHerr** [comment]
yeah this is a bit confusing... but the reports folder is what is important for the crew. these .R script are just part of the CI black box.

**Comment by teixeirak** [comment]
@ValentineHerr , would it be possible to code the rest of these tests (mainly ash census) this week? (And how much of your time do we have left?)

**Comment by ValentineHerr** [comment]
Sorry I had not seen the list was updated. I'll work on that now. I have ~18.5 hours left.

**Comment by teixeirak** [comment]
ok, thanks.

**Comment by ValentineHerr** [comment]
All right, I think I went through all of the items on the list, except the photo one, which I am not sure I can do, as it is unclear how the photos get paired with the data.

I added 2 things on the main repo page: one is the list of the warnings, the other is a map of the blocks with census status (done, warning pending and/or error pending).

Let me know if that works!

**Comment by teixeirak** [comment]
This is great; thank you! I really like that map!

What happened to all the previous errors? Are they already corrected?

**Comment by teixeirak** [comment]
> What happened to all the previous errors? Are they already corrected?

Oh, I see that they're still there. I think that it's confusing to highlight the warnings so much more strongly than the errors. I'm going to edit the .md to fix this.
