### ISSUE TITLE
test results updating

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#21]
@ValentineHerr , I fixed an error (issue #20 ) and confirmed that it was fixed in the Excel file, but the error report has not updated. Specifically, I fixed the error in the first record in [this file](https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/testthat/reports/requires_field_fix/dead_but_crown_thinning_less_than_5.csv) (tag #80005 in quadrat 801), confirmed that it was fixed in the Excel file, and then waited for the GitHub action to finish, but the record remains in that file. 

Then, looking around more, I noticed that there are near-repeat records in [this file](https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/testthat/reports/requires_field_fix/status_A_but_unhealthy.csv), where Qx and Qy changed.

Together, this makes me think that the error reports are a cumulative record, where new records are added, but old ones are not deleted. Is this the case?

**Comment by ValentineHerr** [comment]
@teixeirak, now the should works again and the file is updated. It was not updated because the test was breaking while making the dashboard map that I didn't code correctly in the CI and also because the new download has Tag and StemTag twice, which made the code obsolete.

**Comment by ValentineHerr** [comment]
I think I can close this

**Comment by ValentineHerr** [comment]
wait, reopening this as I didn't check the issue with Qx and Qy

**Comment by ValentineHerr** [comment]
The issues with Qx and Qy seems to come from the data that is loaded in FFF. @jess-shue, did you change the data in FFF? It looks like Qx and Qy were changed to global coordinates in the last few submissions.
I know in the data I gave you there were a few local coordinates that were wrong (>20) but I don't thins that it was this many.

**Comment by ValentineHerr** [comment]
@teixeirak, 
Those duplicate trees with different Qx and Qy are in the Excel file of the FFF, and it looks like they were visited twice, but the stuff recorded is not always consistent.
Here is an example:
![image](https://user-images.githubusercontent.com/19673377/124359186-e1649a00-dbf1-11eb-8715-5e05ba52afb4.png)

**Comment by ValentineHerr** [comment]
opened a separate issue so can close this
