### ISSUE TITLE
Replace all "Crown thinning"=0 with "Crown thinning"=5

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#22]
@ValentineHerr , All of the records that are recorded as errors in this file (
https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/testthat/reports/requires_field_fix/dead_but_crown_thinning_less_than_5.csv) have the same problem, which is that  "Crown thinning"=0 (not a valid code) should be replaced with "Crown thinning"=5. As it's clunky to fix errors, it would be best if you could code this fix. 

@jess-shue has fixed this in FastField, so we won't see any more instances of "Crown thinning"=0, which means it's safe to just replace all with "Crown thinning"=5.

We'll also want to exclude these from our trace of initial survey errors, as it's no longer possible to make this mistake.

**Comment by teixeirak** [comment]
See issue #20 for the background on this (if needed).

**Comment by ValentineHerr** [comment]
Ok, I need to do this but I think I'll deal with this towards the end of the census, I am worried to mess things up. right now.

**Comment by teixeirak** [comment]
Okay. It may end up being easier to fix this in the corrections process.

**Comment by teixeirak** [comment]
I completed all of these as examples for creating [these instructions](https://github.com/SCBI-ForestGEO/SCBImortality/issues/20). They should disappear with the next data update.
