### ISSUE TITLE
create single log of failed tests

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#23]
@ValentineHerr , it's going to be much easier if we have a single .csv with all the failed tests that require field fixes. This is because we need to identify trees by quadrat, and also want to be able to see trees with the same error. Could you please create such a file, and be sure to include a field indicating the test that failed?  I don't see any need to retain the separate files for each test.

**Comment by teixeirak** [comment]
It would also be helpful to have a single list of quadrats with problems. 

We will need this to be able to efficiently "dispatch" quadrats in FastField back to the app for fixing, so the sooner the better.

**Comment by ValentineHerr** [comment]
[This commit](https://github.com/SCBI-ForestGEO/SCBImortality/commit/c9a7dc0c4960e6963f4b493b9ec097ac44b47831) generates a single log for failed tests (except for the tags missed and duplicated tags).

I also edited the dashboard warning message to add warnings about stuff that will be auto-fixed.

Next, I'll push a list of quadrats with number of errors that require field check and auto-fix error and warnings

**Comment by ValentineHerr** [comment]
Ok I created [this file ](https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/testthat/reports/quadrat_n_errors_summary.csv)with list of quadrats with problems. @teixeirak, I'll let you close this issue if you are satisfied. It also relates to [this comment](https://github.com/SCBI-ForestGEO/SCBImortality/issues/20#issuecomment-873214522).

**Comment by teixeirak** [comment]
Thanks! I'll follow up more later.

**Comment by teixeirak** [comment]
Looks good; thanks.
