### ISSUE TITLE
improving error reports

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#26]
@ValentineHerr , there are two small changes that would improve the error report: 
- please move `error_name` to the beginning of the file (I think this will make it easier in the field)
- in all error report files, please include the surveyor ID, as this will help the team realize who made which mistakes and facilitate future analysis of error rate.

**Comment by ValentineHerr** [comment]
Have any significant number of errors been resolved yet? If not, I'll overwrite the "trace of report" (and start a new one) because adding those 2 columns mess up that part. If yes, ....well it will be more complicated.

**Comment by teixeirak** [comment]
No, but do it now, as @briannakcalkins  is about to work on this today

**Comment by teixeirak** [comment]
In fact, the only errors that have been resolved are ones that I don't want counted in the trace

**Comment by teixeirak** [comment]
> No, but do it now, as @briannakcalkins is about to work on this today

I wasn't thinking right.  This isn't quite so urgent... we just want it before we run the next update.
