### ISSUE TITLE
fixes to tests

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#28]
@ValentineHerr , @rudeboybert 

There's an error in a few of my tests. The following should not be required for dead fallen or missing trees:

missing_crown_position
missing_percent_crown_intact
missing_percent_crown_living

I will fix this in the README

**Comment by teixeirak** [comment]
forgot to flag this issue in the commit: https://github.com/SCBI-ForestGEO/SCBImortality/commit/fa1780b75590c18710b26f25270ad42c1b702eff

**Comment by teixeirak** [comment]
@ValentineHerr, another important error just discovered by @briannakcalkins --

missing_EAB_info should only be triggered if `Crown position < 10 cm DBH` is missing  **for stems <10cm**. The current test gets all stems, which generates a huge number of errors. Fixing this will really clean up our error list!

**Comment by teixeirak** [comment]
@ValentineHerr  and @rudeboybert , we'll want to fix these in both repos before the next data sets are pushed. @briannakcalkins , please don't push new data until we have the fix.

**Comment by ValentineHerr** [comment]
I think fixes those issues now.

**Comment by teixeirak** [comment]
Thanks; looks great!  There's one more, but I'll open another issue.

**Comment by teixeirak** [comment]
@ValentineHerr , I'm reopening to catch some additional bugs:
- [ ] In general, no data should be required for DN (not found) trees. See changes to list of tests in the most recent commit. This accounts for a few of the "errors" detected after @briannakcalkins's fixes yesterday:

<img width="976" alt="image" src="https://user-images.githubusercontent.com/6355854/124947400-cb821b00-dfdd-11eb-982a-3eaae956294a.png">

**Comment by teixeirak** [comment]
- [ ] `status_DS_or_DC_but_DBH_measured` should not be triggered on trees that were previously dead:
<img width="834" alt="image" src="https://user-images.githubusercontent.com/6355854/124949290-6cbda100-dfdf-11eb-8e74-8fda3e9adad6.png">

**Comment by ValentineHerr** [comment]
> * [ ]  `status_DS_or_DC_but_DBH_measured` should not be triggered on trees that were previously dead:
> 
> <img alt="image" width="834" src="https://user-images.githubusercontent.com/6355854/124949290-6cbda100-dfdf-11eb-8e74-8fda3e9adad6.png">

Those are triggered because status 2021 is `DC`. In all those tests, I am looking at status 2021. Should I be looking at status 2020?

**Comment by teixeirak** [comment]
> Those are triggered because status 2021 is `DC`. In all those tests, I am looking at status 2021. Should I be looking at status 2020?

In general, you should be looking at 2021 status. But in the case of this specific test, we only need a DBH if the tree is newly dead.

**Comment by ValentineHerr** [comment]
Ok, next CI update should have those fixed.

**Comment by teixeirak** [comment]
Thanks! Will other missing data tests be triggered by DN?

**Comment by teixeirak** [comment]
(So far,  missing_EAB_info is the only one that's been triggered, which makes sense because it's hard to miss a >10cm stem.)

**Comment by ValentineHerr** [comment]
> Thanks! Will other missing data tests be triggered by DN?

yes, but you know what, I could just remove everything with current status `DN` before even testing anything, that way none of the test will return those. okay?

**Comment by teixeirak** [comment]
Sure, makes sense. We'll want to make sure that this gets mirrored in the Harvard repo (@rudeboybert )

**Comment by teixeirak** [comment]
@ValentineHerr , one more here: 
- [ ]  FAD only needed on previously living trees : https://github.com/SCBI-ForestGEO/HarvardMortality/issues/13.

**Comment by ValentineHerr** [comment]
The latest update in the list of tests should be implemented now (once CI is completed).

**Comment by teixeirak** [comment]
I'm closing this, as I've opened separate issues for other fixes.
