### ISSUE TITLE
read_xlsx() reading numeric columns as character

### ISSUE THREAD

**Issue by rudeboybert** [SCBI-ForestGEO/SCBImortality#30]
Unbeknownst to me the `read_xlsx()` function used in `Generate_reports.R` was reading some numeric variables as character variables. (@teixeirak this was the source of https://github.com/SCBI-ForestGEO/HarvardMortality/issues/5): I added this code to fix the issue for the HF data.

```r
# Convert character vectors to numeric
mort[, "DBH"] <- as.numeric(mort[, "DBH"])
mort[, "HOM"] <- as.numeric(mort[, "HOM"])
mort[, 'Percentage of crown intact'] <- as.numeric(mort[, 'Percentage of crown intact'])
mort[, 'Percentage of crown living'] <- as.numeric(mort[, 'Percentage of crown living'])
```

For SCBI this is only a problem for `DBH` and `HOM`, but it still might be worth to have explicit checks for all cases

**Comment by teixeirak** [comment]
@ValentineHerr , this is one for you to check.

**Comment by ValentineHerr** [comment]
Yes, I've used `as.numeric(mort[, "DBH"])` but I never used `HOM`. Did I miss a test that needs `HOM`?

**Comment by teixeirak** [comment]
No, there's no test with that.

**Comment by ValentineHerr** [comment]
Ok thanks. I think  we can close this issue.
