### ISSUE TITLE
wrong set of trees in fastfield

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#31]
@jess-shue , @ValentineHerr ,

@briannakcalkins is reporting to me (from the field) that we have some trees identified as ones that should appear in the census that are not in FastField. Here's a list:

![image](https://user-images.githubusercontent.com/6355854/124812047-23167d00-df31-11eb-90a7-40f9f5de513c.png)

I will see if I can understand what's going on here

**Comment by teixeirak** [comment]
here are the trees that @briannakcalkins found missing in FastField:
<img width="1181" alt="image" src="https://user-images.githubusercontent.com/6355854/124830248-9aefa200-df47-11eb-854f-08b790804048.png">

They are mostly <10cm fraxinus/ CHVI, but I can't claim any insight as to why they may be missing....

**Comment by jess-shue** [comment]
@teixeirak I used the mortality 2020 data from GitHub to make the background data from the app. It looks like 23547 and 23597 were not in that data set. Otherwise, it appears to be an issue with my subsetting the data in R to exclude stems < 10 cm DBH unless they were ash or Chioanthus. I will work on updating that data and the app this evening.

**Comment by jess-shue** [comment]
OK, the background data have been updated and so has the app - everyone should update the app on their iPads before going into the field - Version 13 of the form. Some of the issues stem from my misunderstanding of the data and some from the subset function in R.
*23547 and 23597 were not in mortality 2020 and so I did not add them back in (23597 was listed by @briannakcalkins  but not by @teixeirak )

**Comment by teixeirak** [comment]
Thanks, @jess-shue ! 

@ValentineHerr , do you perhaps have any insight into what's going on with these stems? This may also relate to the fact that you found stems missing in 2020, but Cameron tells me he was conscientious to  find every tree in the census (and there are none missing in his field data sheet). 

This is all evidence that our error detection system is working as designed!

**Comment by teixeirak** [comment]
@briannakcalkins , you sent me a text from the field related to this issue. Could you please provide some more details here (if you think there's a new problem).

**Comment by briannakcalkins** [comment]
Hey everyone! So, as mentioned earlier there were missing stems that weren't included in Fast Fields. However, when adding these missing stems, there was a large increase in the amount of stems per quadrat. When Jen and I were doing quadrats today, there was twice the amount as expected in each of them, and for a lot of the smaller ones just added, there wasn't any information regarding their status last year, what their diameter is, etc. So it was nearly impossible to find most of the new ones not originally included. Also, since so many stems were added, I noticed now theres a ton of missing stems from all of the quadrats that I've already moved through, and I'm guessing this will be a difficult fix when comparing how today went with the mortality census.

**Comment by teixeirak** [comment]
@briannakcalkins , were there species added besides Fraxinus and CHVI?

**Comment by jess-shue** [comment]
@briannakcalkins  Thanks Brianna, sorry about the trouble. 
@teixeirak Could I have some clarification on the mortality data? This is because I'm not working with census data, so I'm not entirely sure what to exclude for this survey. Let me get back to you with more specific questions.

**Comment by teixeirak** [comment]
@briannakcalkins , the record of missing stems (https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/testthat/reports/requires_field_fix/quadrat_censused_missing_stems.csv) indicates that at last count there were 217 missing in the census so far, so on average <1 per quadrat. From your description it sounds like far more than that were added.

**Comment by teixeirak** [comment]
@jess-shue , let's exclude any where previous year was status DC or DN.

**Comment by jess-shue** [comment]
@teixeirak So, exclude if status.2020 is 'DC', 'NA', or 'PD'? There are no 'DN's listed within the status.2020 column
Sorry, I had originally approached this as I had at SERC and HF, but it is more complicated than regular census data.

**Comment by jess-shue** [comment]
@briannakcalkins and @teixeirak Will you be working in the field tomorrow? If so, I will revert the form back to the previous data - which will still have those missing stems, but will eliminate the additions made yesterday. We are supposed to have bad weather here and so I can work on this issue and clean things up more easily tomorrow.

**Comment by teixeirak** [comment]
I don't think they'll be in the field tomorrow, but I'll let @briannakcalkins confirm.

**Comment by teixeirak** [comment]
> @teixeirak So, exclude if status.2020 is 'DC', 'NA', or 'PD'? There are no 'DN's listed within the status.2020 column
> Sorry, I had originally approached this as I had at SERC and HF, but it is more complicated than regular census data.

Correct.

Also, let's exclude any <10 cm Fraxinus/ CHVI that were dead the previous year (including standing). No need to track those until they fall.

**Comment by briannakcalkins** [comment]
Hey so sorry for the late message, I went to bed. I was planning on going to the field today, which was why I was worried about the issue. It says there was only 217 stems, but I think way more were added to the forms. Some of the new trees were Fram and CHVI, but a lot of them were titled "unk" with little information as well as what Jen mentioned, how some of the trees were labeled as PD but really were fine and healthy. Weird errors

**Comment by briannakcalkins** [comment]
I should be at the field by 10 am today, so let me know in the meantime if I should go out or wait for next Monday. Thanks!

**Comment by teixeirak** [comment]
@briannakcalkins , I'd say it should be fine for you to go. 

There are also a lot of previous errors to revisit (I've dispatched ~10 more columns), and it would be best to focus on those first anyway.
You can also look for trees that were missed according to the list on this repo, using that rather than the list in FastField as a guide to what you should expect. 

@jess-shue is usually fast, so I'm guessing she'll be able to revert to the previous version quickly, but worst case scenario , if you run out of dispatches and need to work on new quadrats, you should just skip any trees that are:
- <10 cm and a species other than Fraxinus (FR_ _) or CHVI. 
- <10 cm Fraxinus/ CHVI that were dead the previous year (including standing)
- status.2020 is 'DC', 'NA', or 'PD'
That should solve the problem, right?

**Comment by jess-shue** [comment]
@briannakcalkins I have restored the previous version of the data into the app for now. It won't change the app version, but when you click on 'Forms' on the main page you should see it update - it may happen very quickly - before opening the form itself.

**Comment by teixeirak** [comment]
Thanks @jess-shue !

**Comment by jenajordan** [comment]
Hi @briannakcalkins , @jess-shue , @teixeirak -  just seeing this thread (as of today I'm done with my summer Forest Biogeochem grad course today - so I now have more time to dig into Github/ R/ etc). To confirm, 2 days ago at SCBI, each quad I was in had 25-28 stems in it, whereas at prior visits, quads had 8-17 stems. A number of stems in FF appeared <10 cm (not Frax), most stems were noted as "n/a" in the last census, a number were noted as "PD" in last census but were alive, some trees  > 10 cm in the quad weren't in FF, and a large # of the trees noted in FF could not be found (dead?). All of this wasn't the case at prior visits. Due to these challenges, completing a quad was slow going. Hoping to get out for multiple days this coming week & will focus on fixing errors.

**Comment by teixeirak** [comment]
@jenajordan , we're working on fixing this, but have reverted to the previous version that did not have all those extra trees. Sorry for the complication, and rest assured that we're not going to be trying to census all those!

**Comment by jess-shue** [comment]
Hi All, @teixeirak @briannakcalkins @jenajordan 
Sorry for the back and forth with the data. I had thought a quick fix had worked, but had not, and so the form was reverted to the first set of data Friday morning. 
I've made a third attempt at updating the dataset that is used by FFF's and should be updated for you tomorrow if you update the app before going to the field. If this still creates issues, it may be time to have a Zoom discussion with @teixeirak as it seems I am struggling to get the dataset into the proper subset; maybe I am making things too complicated, but with multiple columns with differing data there is no one simple solution I can find to make this happen.

Some of the questions/issues I'm having about the mortality census in 2020:
- There are over 1000 stems in the mortality_2020.csv that were some form of 'D' in 2018 but were 'A' for status.2020
- Were all stems > 100 mm (10 cm DBH) censused? I know there was certainly mortality from 2018 when DBH's were last taken, but it seems some trees > 100 mm in 2018 have 'NA' for status.2020 - quite possible
- Some trees in status.2020 were 'NA' but were not recorded as Dead in status.2019 or status 2018; some with DBH's in 2018

**Comment by teixeirak** [comment]
Sorry this has proved complicated!

@jess-shue , the most critical would be that you and @ValentineHerr are using the same list of expected trees.  Can you two please coordinate on that? Talking to me wouldn't be much help, as I didn't create past data sheets and don't know the details of how they were made. My role here would be to make judgement calls on what we want to exclude/ include.

It sounds like we have some past data issues (that first bullet point is concerning), and I'm glad we're getting a system in place that will hopefully avoid that in the future.

**Comment by ValentineHerr** [comment]
@jess-shue,

I look at the last main census data and only keep trees that were alive and > 10cm (except for fraxinus and Chionanthus virginicus).

So maybe the best way to deal with this would be for your to use this and merge the latest mortality census status, when it exists?

```r
# load and clean up the 3rd main census ####
main_census <-  read.csv(paste0("https://raw.githubusercontent.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/master/tree_main_census/data/census-csv-files/scbi.stem3.csv"))

## convert dbh to numeric
main_census$dbh <- as.numeric(main_census$dbh)

## only keep trees > 10cm except for fraxinus and Chionanthus virginicus
main_census <-  main_census[grepl("^fr..|^ch..", main_census$sp) | (!is.na(main_census$dbh) & main_census$dbh >= 100), ]

## remove trees that are dead
main_census <- main_census[!main_census$status %in% "D",]

```

**Comment by teixeirak** [comment]
I think we could also skip stems that are:
- status.2020 is 'DC', 'NA', or 'PD'
- <10 cm Fraxinus/ CHVI that were dead the previous year (including standing) -- after the correction related to issue #8.

**Comment by jess-shue** [comment]
Thanks @ValentineHerr. It would be much simpler to start from the census data rather than the mortality file. I believe we were trying to use the mortality 2020 data to help further inform and reduce the stem list for the background data in the app, but that appears to be causing the issues.

At SERC and HF we've included dead stems. This may be something to discuss with Dan Johnson.

@teixeirak The status.2020 from the mortality census is confusing. There are a handful of stems listed as 'PD' that were not dead in 2019, but some were listed as dead in the 2018 census. 'NA' in status.2020 is also problematic as many were also 'NA' in 2019. However, in the 2018 census they were alive and had DBH's recorded and ~1,700 were > 10 cm. Were some stems not checked during the mortality survey?

**Comment by jenajordan** [comment]
@jess-shue @teixeirak @ValentineHerr Not sure this adds much (& I noted it before), but last Thurs (when there were many more stems noted in FF) was the 1st and only time I found a significant # of trees in FF noted as "PD" that were alive. Prior to Thurs, this was not the case.

**Comment by jess-shue** [comment]
Thanks @jenajordan. Just to clarify:  That was the second set of background data in which I had tried to use the status.2020 to filter out stems and realized some 'PD' stems in 2020 were never recorded as dead previously. Obviously, it was not the correct way to handle things and produced the issues you saw.

**Comment by teixeirak** [comment]
@jess-shue , 

I was just out in the field with @briannakcalkins  and @jenajordan , and we're still having problems with the set of trees in FastField. It seems that we're still stuck on the previous form version with all those extra fields. 

1. @jess-shue , are you sure that the old version was properly restored?  
2.  We'll still want to refine this list, and I'll come back to this, but item 1 is fairly urgent, as that "new", reverted version had a  lot of problems that hamper progress in the field.

**Comment by teixeirak** [comment]
# Examples of errors in tree set
*(@briannakcalkins , @jenajordan , you can help contribute cases here)*:
- [ ]  60531 in quad 611 is an example of a tree that should be excluded, as opposed to registering an error that it's missing

**Comment by jenajordan** [comment]
@teixeirak , before I add to "example of errors in tree set", clarifying - do I list here trees noted in the "missing stem" spreadsheet yet not noted in FF? And/or do I list trees that I notice are in FF but should not be (i.e. <10 cm)?

**Comment by jess-shue** [comment]
@teixeirak I really feel that we should revert to using census 3 data to eliminate these issues - missing trees should be eliminated by using that data and what to exclude would be much simpler. We know that a tree or two are missing from the mortality data as I reported earlier. The app was updated, but if folks didn't connect to WiFi before going into the field the list of data would not have updated.

@briannakcalkins @jenajordan I have reverted back to June 4th's version of the data that was in use prior to last week as it had the least number of issues. Please connect to WiFi, open the app and click on forms, and you should see 'Form Updated' briefly appear at the top in a grey box just above the name of the form.

**Comment by teixeirak** [comment]
> @teixeirak I really feel that we should revert to using census 3 data to eliminate these issues - missing trees should be eliminated by using that data and what to exclude would be much simpler. We know that a tree or two are missing from the mortality data as I reported earlier. The app was updated, but if folks didn't connect to WiFi before going into the field the list of data would not have updated.

This is what @ValentineHerr  is doing, as in [this comment above](https://github.com/SCBI-ForestGEO/SCBImortality/issues/31#issuecomment-878241862), so I agree that that's what we should do. 

On top of that, I believe it would be helpful to drop some of the trees we know to be dead (according to criteria I listed above), but that's secondary.

**Comment by jess-shue** [comment]
@teixeirak  OK, I will update the app quickly with the 3rd census data. As mentioned in [this comment above](https://github.com/SCBI-ForestGEO/SCBImortality/issues/31#issuecomment-878255780), we are assessing previously dead trees at SERC and HF. This may be a broader protocol discussion needed to be had with Dan Johnson.

**Comment by teixeirak** [comment]
> @teixeirak , before I add to "example of errors in tree set", clarifying - do I list here trees noted in the "missing stem" spreadsheet yet not noted in FF? And/or do I list trees that I notice are in FF but should not be (i.e. <10 cm)?

Hopefully we'll have major progress on this soon, but generally it would be helpful to have an example or two of any type of error you encounter. It's best when you can identify patterns behind problems. Any time you discover a new problem, you can open a new GitHub issue.

**Comment by teixeirak** [comment]
> @teixeirak OK, I will update the app quickly with the 3rd census data. As mentioned in [this comment above](https://github.com/SCBI-ForestGEO/SCBImortality/issues/31#issuecomment-878255780), we are assessing previously dead trees at SERC and HF. This may be a broader protocol discussion needed to be had with Dan Johnson.

Thanks! That will solve the main problem. 

It could make things more efficient to eliminate trees known to have already died and fallen (I wouldn't eliminate still-standing trees, which are the ones of interest for Dan's grant). This is particularly true of the small ash trees (not part of the censuses at other sites anyway). That's a secondary issue, though.

**Comment by jess-shue** [comment]
@briannakcalkins @jenajordan 
The app is now on version 14, please update before heading into the field. For today, the coordinates are back to 'global' coordinates and are not at the quadrat level. I will update those later today.

**Comment by jess-shue** [comment]
@briannakcalkins @jenajordan @teixeirak 
I was able to update the lookup data once again this afternoon. Please let me know if you have any forms 'In Progress' - if so I'll wait to update the app until they are completed.
I have removed stems with a 'DC', 'DN', or 'DT' code but left any with a 'DS'. I also added the local coordinates back into the data. Sorry you had to work without them today, but I didn't have time this morning to make that happen right away.

**Comment by jess-shue** [comment]
@briannakcalkins @jenajordan Please update the form again before going into the field. The QX and QY are now updated to the local coordinates within the 20x20 m quadrats. There are a few trees with negative or strange coordinates that are likely listed in the wrong quadrat, but it is fewer than 10 and I sent a list in issue #33.

**Comment by teixeirak** [comment]
thanks, @jess-shue !

@briannakcalkins and @jenajordan , if time permits, I'd encourage you to spend some time reviewing the errors, missing trees mentioned above, and potentially going in to check things in the FastField app. This can help ensure that we caught all the needed fixes/ that everything looks right with the system. I'm going to give it a brief look now.

**Comment by teixeirak** [comment]
> @briannakcalkins and @jenajordan , if time permits, I'd encourage you to spend some time reviewing the errors, missing trees mentioned above, and potentially going in to check things in the FastField app. This can help ensure that we caught all the needed fixes/ that everything looks right with the system. I'm going to give it a brief look now.

...but note that the latest checks run failed, so results aren't fully up-to-date.

**Comment by teixeirak** [comment]
> I have removed stems with a 'DC', 'DN', or 'DT' code but left any with a 'DS'. I also added the local coordinates back into the data.

@ValentineHerr , have you also removed these?

**Comment by ValentineHerr** [comment]
> @ValentineHerr , have you also removed these?

I'll double check tomorrow

**Comment by ValentineHerr** [comment]
In my code I remove all trees with status "D", which includes codes like DC, DN, DT and DS.
I could make it that it includes the trees with code "DS", but that would include quite a bit more missing trees...
Before I do so I want confirmation that it is worth it, because reverting this would get complicated with the "trace of reports".

**Comment by teixeirak** [comment]
We do need to keep the DS>10cm, as we want to track any trees (dead or alive) that might be seen from above. No need to track dead fallen or DS <10cm.

We do need to make sure we're matching what @jess-shue did.

**Comment by ValentineHerr** [comment]
ok done

**Comment by ValentineHerr** [comment]
I think we can close this
