### ISSUE TITLE
 fix `status_A_but_unhealthy` test

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#32]
@ValentineHerr , I don't understand why we're getting some trees that aren't status A for the  `status_A_but_unhealthy` test.

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/6355854/124814604-3840db00-df34-11eb-8c35-5f01aca92dde.png">

Also, this doesn't require a field check in all cases. I will modify the test list accordingly.

**Comment by teixeirak** [comment]
maybe those are showing up because they are duplicates of trees that do meet this criteria?

**Comment by ValentineHerr** [comment]
> maybe those are showing up because they are duplicates of trees that do meet this criteria?

yes, that is why. I haven't spent time with this duplicate issue. Not sure I understand it well enough, were trees visited twice? I am surprised the info recorded is so different. I hope FFF is not mismatching things.

**Comment by teixeirak** [comment]
You're right, that is strange... The different records are in the same commit. Seeing if I can figure anything out from the raw file....

**Comment by teixeirak** [comment]
The raw file does have two very different records for  HAVI tag #20537 (not that that precludes a FFF mess-up):
<img width="1223" alt="image" src="https://user-images.githubusercontent.com/6355854/124828600-7c88a700-df45-11eb-8995-e6d80db935a8.png">

 I'm flagging @briannakcalkins and @jenajordan to see if they understand this. Perhaps a mix-up of trees?

**Comment by ValentineHerr** [comment]
I think we can close this
