### ISSUE TITLE
Negative lx and ly - check quadrats

### ISSUE THREAD

**Issue by jess-shue** [SCBI-ForestGEO/SCBImortality#33]
@briannakcalkins @jenajordan @teixeirak  When Valentine recalculated the local coordinates, some trees had a negative y coordinate. It is likely these trees may be assigned to the wrong quadrat. Would it be worthwhile to check the quadrats of these stems? 
[negative_local_coordinates.xlsx](https://github.com/SCBI-ForestGEO/SCBImortality/files/6780808/negative_local_coordinates.xlsx)

**Comment by jenajordan** [comment]
We could do that, yes. Btw, I started on the mortality census in the deer exclosure this past week. There seemed to be some stems <10 cm noted in FF (I did not measure DBH),& a few > 10 cm not in the census, & there was an unusual # of stems I could not find there - in the 4 quads I did.

**Comment by ValentineHerr** [comment]
I think we can closing this (not sure the trees were visited to check their quadrat and/or coordinates but we are not going to deal with this here).
