### ISSUE TITLE
understanding the dashboard map

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#34]
@ValentineHerr ,

On the dashboard map, do "errors" (coded orange) include those that will be automatically fixed? Do they include missing trees?

I think the most helpful would be to indicate:
(1) errors requiring field fixes, including missing trees 
(2) errors that will be automatically fixed  +  warnings 

That said, since we're already archiving versions for @rudeboybert 's paper, it probably doesn't make sense to to change it at this point.

**Comment by ValentineHerr** [comment]
The map is only showing errors requiring field fixes, and warnings... sorry...

**Comment by teixeirak** [comment]
It's okay (probably best, actually) to not map errors that will be auto fixed.  Does it include missed trees?

**Comment by ValentineHerr** [comment]
no... I could make a separate map for that or just update this one and we start the "sequence" today.

**Comment by teixeirak** [comment]
I think it's best to add it. We do have the first set of fixes in, so we'll need to retroactively make one map for the sequence. Alternatively (probably easier), we could revert the commit with new data from last night get a map with the old data, and then redo the commit.

**Comment by ValentineHerr** [comment]
I'll try that on a separate branch

**Comment by ValentineHerr** [comment]
oh! actually, I do have the missing stems in there. They are considered as errors in the map.
I thought it was odd I didn't add those, but they are automatically pulled in when the script looks at all the CSV files in `reports/requires_field_fix`.

So I think we are good and can close this issue

**Comment by teixeirak** [comment]
oh, great! Thanks!
