### ISSUE TITLE
D.shaped.exit.hole.count must be filled "0" if there are none

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#35]
@briannakcalkins , I'm reviewing the errors that persisted after your fixes yesterday. Most of them seem to because of NA's in D.shaped.exit.hole.count:
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/6355854/124948477-b8bc1600-dfde-11eb-8153-dd1067bc8f1e.png">

**Comment by teixeirak** [comment]
These are legitimately NA if `DE` is not included in the EABF field. @ValentineHerr , we'll want to modify the tests accordingly. I'll fix the list of tests when I have a moment.

**Comment by teixeirak** [comment]
@ValentineHerr , this is a common unnecessary error. Could you please fix it as soon as you get a chance? 

Specificially, "missing_EAB_info" should not be triggered if `D.shaped.exit.hole.count` = NA unless `DE` is selected in the EABF field.

**Comment by ValentineHerr** [comment]
should be done now.

**Comment by teixeirak** [comment]
Thanks! This should clean up a  lot of errors. Looks like the tests failed to run though.

**Comment by ValentineHerr** [comment]
ha... sorry, I didn't have the time to wait for it and I am back at it only now. Will fix it once I understand what is going on.

**Comment by teixeirak** [comment]
Thanks!
