### ISSUE TITLE
Test 9 implemented?

### ISSUE THREAD

**Issue by rudeboybert** [SCBI-ForestGEO/SCBImortality#37]
In the [list of tests](https://github.com/SCBI-ForestGEO/SCBImortality/tree/main/testthat), has test 9 been implemented? For newly censused trees (DS or DC) is `percentage of crown living` == 0? I couldn't locate it in `Generate_reports.R`

**Comment by ValentineHerr** [comment]
Hmmm.. you are right, I don't see it either. I must have missed it.
I'll code this tomorrow.

**Comment by ValentineHerr** [comment]
Thanks for catching this @rudeboybert ! I implemented the test.
