### ISSUE TITLE
make report files more user-friendly

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#39]
@ValentineHerr , I learned today that it's actually quite clunky to use these report files in the field! There are a few changes that would make a dramatic difference (and the sooner you can address these, the better for field progress):

- [x] combine missing stems into the field error fix file (to avoid having to toggle between files)
- [x] sort `quadrat_n_errors_summary` and the field errors fix file by quadrat (currently the former is sorted by n errors, which is hard to navigate). Also, in  `quadrat_n_errors_summary`, please include the sum of missing stems and erroneous records (makes it easier to ID quadrats for dispatch)
- [x] resolve issue #38

**Comment by ValentineHerr** [comment]
should be done now.

**Comment by teixeirak** [comment]
Thanks, @ValentineHerr !  I'm not sure issue #38 is solved correctly, but the reports look great, so we can close this issue.
