### ISSUE TITLE
allow AU status with if crown living <100% but no FAD

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#40]
@ValentineHerr , could you please modify the code such that a tree can be AU if crown living <100% but no FAD? There are no FAD's selected?

We'll want to mirror this at Harvard Forest (@rudeboybert ).

**Comment by ValentineHerr** [comment]
should be done now.

**Comment by teixeirak** [comment]
Thanks!

**Comment by teixeirak** [comment]
@ValentineHerr , could you please revert this commit? Dan wants there to always be an FAD. 

@briannakcalkins and @jenajordan , for AU trees with crown thinnning but no visible FAD, please selece "unable to determine".
