### ISSUE TITLE
how do we get rid of erroneous records

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#41]
This is a question that @jenajordan , @briannakcalkins , and I ran into today-- probably a question for @jess-shue -- 

How do we get rid of erroneous records? For example, if there's a good record but then an incomplete record for the same tree was later entered? Or when half a quad was censused and then a fixed version with all trees was submitted. 

This relates to the handling of duplicates.  I can't dig into this right now, but wanted to register it.

**Comment by jess-shue** [comment]
@jenajordan @briannakcalkins @teixeirak 
If the extra stem is created in the app, and you are still editing:  use the '< Back' button at the top of the stem/mortality form to go to the list of trees. The list includes the quadrat name, tag, stem tag, species code, and status. You can click on the entry and edit it, or to delete a duplicate simply swipe to the left and a red 'Delete' button appears.
![stem_list_FFF](https://user-images.githubusercontent.com/37407801/125781285-122fad1f-5031-480a-9244-f4420a633b43.png)
![stem_list_delete_FF](https://user-images.githubusercontent.com/37407801/125781305-7ff3af7b-9036-45c4-a979-3c56a26af64c.png)


If forms have been submitted, that would require going to the submissions section of FFF's and deleting the unnecessary submission from there.
