### ISSUE TITLE
resolve error: some trees in census as ash were actually hickories

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#47]
from @mageeluke : "a couple of ash were actually hickories and, as a result, I didn’t record EAB info. Those will likely stay as errors on the map, however."

Luke, could you please provide tag numbers or tell us where this is noted?

**Comment by mageeluke** [comment]
I had the following notes. Although, I'm not totally certain on picking apart C. glabra from C. ovalis. 

Tag 093481: species should be Carya cordiformis 
Tag 093487: species should be Carya glabra

**Comment by ValentineHerr** [comment]
also here are non fraxinus species tat got some eabf info (may be already resolved later in my script by I need to revisit it):

![image](https://user-images.githubusercontent.com/19673377/149548580-29ff126b-1407-400c-a7db-7ed47aa401a7.png)

**Comment by ValentineHerr** [comment]
Note: species identification errors in the main census data should be dealt with in [this repo](https://github.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/tree/master/tree_main_census/data/census-csv-files). Then, anything that needs to happen to reconcile the species names in the mortality files should be coded in a new row of [this file](https://github.com/SCBI-ForestGEO/SCBImortality/blob/df08e9a47ab6518cbd541d81182e745f45541ac8/raw_data/manual_fixes.csv) (which should only fixes mortality files).
