### ISSUE TITLE
resolve duplicates

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#48]
from Luke: "Overall, all of the stems and info appear to be there. There are a significant number of duplicates, and few of the outstanding errors (with missing data) have the information collected in a separate, duplicated submission. Not sure the best way to tackle this."

@mageeluke or @briannakcalkins , it would help to have some more info on this. Would the latest entry consistently be the better one, or is it mixed? Would it be possible to code the process of selecting the better entry (e.g., latest entry, or entry with no errors), or does this need to be done manually?

**Comment by mageeluke** [comment]
Yes, this is a little tricky. Initially, it looks as if there were several quads that were censused twice (503, 508, 509, 709, 815, 816, 817, 818, 1114), and these could be quickly scanned for significant mismatches (e.g., Dead vs Alive). If there are any significant differences, these could be changed through FastFieldForms. This should cut the duplicates in half. For the remaining duplicates, the same comparison could be done, changing any any submissions with significant differences. 

Unfortunately, I don't think many (if any) have errors, and some of the duplicates were included in the same submission. There may be a better way to select stems, but I'm not sure.

**Comment by teixeirak** [comment]
@ValentineHerr , what's the current method of selecting among duplicates?

**Comment by ValentineHerr** [comment]
I didn't implement any rules yet.

**Comment by teixeirak** [comment]
We don't have a lot of bandwidth for going back and doing field checks, or even spending a long time reviewing hundreds of records. We might just create a general rule (e.g., 2nd survey is accepted). But first a few questions:
(1) Were all errors resolved in both sets of duplicates? (i.e., are there some duplicates with errors?) If there are some duplicate records with errors, those obviously get discarded and we use the complete record. 
(2) How many non-identical duplicate records do we have?

**Comment by mageeluke** [comment]
Yes, all of the duplicates are error free --that was one of the issues with many of those last field check errors.

 A decent percentage (~40% or 175) of these will be mismatching because of crown codes (% remaining and intact); however, significant differences are much, much rarer (e.g., dead vs alive). One suggestion would be would be to take those twice-censused quads and select based on surveyor. 

Overall, the "Warnings" are of much greater concern, in my opinion. I would be happy to discuss further, if it would be helpful. I can commit time on Friday. I don't think it would take too long with a collaborative effort to address the duplicates.

**Comment by ValentineHerr** [comment]
@mageeluke, did you want me to run the script for checks before you push the fixes you made on Friday (assuming you did those in FFF)?

**Comment by mageeluke** [comment]
@ValentineHerr, I have not pushed the new FFF data to GitHub yet. Should I do that? I think it might be good to rerun the script after applying the code used in filtering duplicates?

**Comment by teixeirak** [comment]
I'm downloading the data now and will push once it's ready.

**Comment by teixeirak** [comment]
okay, it's pushed.

**Comment by teixeirak** [comment]
Looking over these, it seems there's often a difference in thoroughness of the record. I'd put greater trust in a record that has an FAD recorded than one that doesn't, or in  one where DBH was measured because it was dead. Would you agree, @mageeluke ? If so, we could go through and hand-select records for these.

**Comment by teixeirak** [comment]
I also wonder... would it be better just to select the latest record?

**Comment by ValentineHerr** [comment]
> I also wonder... would it be better just to select the latest record?

(quite a few have same date)

**Comment by mageeluke** [comment]
I agree, @teixeirak, that the more thorough record should be selected. One of the checks I did on FFF was to see if any of the duplicates labeled as 'AU' had photos, but they did not. I was hesitant to delete records in FFF, but can do that if it would be helpful? Overall, it seems like hand-selecting these records could work (either through FFF or code).

**Comment by teixeirak** [comment]
I'd say it's okay to delete. We have the older versions preserved in GitHub. We'll just want to be sure to tag the commit with the label that records were deleted.

**Comment by teixeirak** [comment]
> > I also wonder... would it be better just to select the latest record?
> 
> (quite a few have same date)

What if we were to order first by date (later date gets higher priority) and then by Bri?

**Comment by mageeluke** [comment]
@teixeirak , I have addressed the remaining problem duplicates on FFF. I submitted all forms back to FFF. It should be ready to push to GitHub. Thank you.

**Comment by teixeirak** [comment]
I've pushed that latest data (forgot to note that here earlier).

**Comment by ValentineHerr** [comment]
Thanks @teixeirak and @mageeluke. Now there is not more duplicates that have different status.2021, fad or eabf.
I am keeping bri first, then latest, but it is easy to change if we want to do the opposite.

**Comment by teixeirak** [comment]
Great, thanks! I think we can close this now.
