### ISSUE TITLE
error in quad 816

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#49]
@briannakcalkins , @mageeluke , I just spent a fair amount of time trying to resolve the issue in 816, which is just changing A to AU:  
<img width="1208" alt="image" src="https://user-images.githubusercontent.com/6355854/130135574-a08b389f-c835-4aad-b0a5-558bb196b407.png">

I'm confused by multiple records in FastField (and apparently a new dispatch system), and made the problem worse with my [attemped fix](https://github.com/SCBI-ForestGEO/SCBImortality/commit/b41f13dafc07b0383fa34b744afb2870f07660ed). I reverted that commit. 

Can either of you help?

**Comment by teixeirak** [comment]
I'm a bit tempted to just edit it in Excel, but that would have to be repeated each time there's a new download from FastField.

**Comment by mageeluke** [comment]
Yes, it looks like the entire quad got recensused. This was the a quad (08 column) I worked on back in June. I can change this in FastFields. The other submitted record (recensused 80694) should be okay.

**Comment by mageeluke** [comment]
@teixeirak this should now be fixed in the latest FastField submissions.

**Comment by teixeirak** [comment]
Yes, it is, and we've gotten rid of all errors!
