### ISSUE TITLE
EAB census update

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#5]
Jess asks:  
*​For the ash and Chioanthus:  do you want crown thinning, epicormic growth, EABF and DE count for both species? Do you want definitions or just values for these columns for the crew to select?*

I'm going to assess whether it's worth it to keep collecting all of these in the 2021 census forward.

**Comment by teixeirak** [comment]
Current guidance:	*For all Fraxinus species and trees code chvi (dead or alive): All trees ≥1 cm will be visited during a mortality survey. :*

- Record crown position (D, DC, I, S, OG)
- Estimate crown thinning via visual assessment per Smith/Flower 2013 (5-point scale)
- Epicormic shoots: Use the 6-class dwarf mistletoe rating system (Hawksworth 1977) to evaluate epicormic growth
- Record EABF (Emerald Ash Borer Factors), separated by comma.
- If DE are present then count all visible D-shaped holes around the circumference of the tree in an area ~50 cm long at breast height and record this number. At SCBI almost all tags are located at 1.3 m, so use the tag as reference to visually define the 50 cm area.

**Comment by teixeirak** [comment]
>     * Record crown position (D, DC, I, S, OG)

**Comment by teixeirak** [comment]
@jess-shue , I'm afraid that upon closer inspection, the estimate of crown thinning that we've been doing won't quite align with the % crown thinning (see [visual guide](https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/Protocols/Mortality-Protocol-2021.pdf)). I think we should add that to the FastField form.

**Comment by jess-shue** [comment]
@teixeirak OK, the crown intact and crown living estimates don't align with the ash crown thinning, correct? The app currently has the crown thinning categories for ash (from your visual guide) in the ash section.

**Comment by teixeirak** [comment]
Great, thanks! At least in theory we're all set with the EAB add-on then. I'll try to review the form itself later today.

**Comment by teixeirak** [comment]
Thinking more about the EAB exit hole count:
- [Knight et al. 2013](https://www.nrs.fs.fed.us/pubs/jrnl/2013/nrs_2013_knight_001.pdf) mention the count in their methods but didn't present any results on exit hole density (though they did use exit holes as confirmation of EAB at the sites)
- [Flower et al 2013](https://www.nrs.fs.fed.us/pubs/jrnl/2013/nrs_2013_flower_002.pdf) used exit holes (along with woodpecker holes and larval counts) to get an EAB density count, which correlated well with delta13C and canopy condition. 
- [Jennings et al 2016](https://www.fs.fed.us/nrs/pubs/jrnl/2015/nrs_2015_jennings_002.pdf) looked at exit holes + woodpecker activity. Again, this was quite a bit more detailed (also counting woodpecker holes, galleries)....

**Comment by teixeirak** [comment]
At least for now, we are continuing with the EAB exit hole count.
