### ISSUE TITLE
plan trees to core

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#50]
This is just a placeholder/ reminder.

- Be sure to include any trees that had dendro bands.

**Comment by teixeirak** [comment]
@RHelcoski and @jenajordan , let's start planning the tree coring.

## Big picture plan:
1. rank trees found dead in order of priority 
2. Do as many as we can in one day with Ryan, probably with Jen helping, and hopefully myself as well
3. If Jen wants to do more on her own later, that's welcome but not required

## Ranking criteria
1. any trees with dendro bands 
2. any tree above 50? cm DBH 
3. random sampling of smaller trees
4. by species: oaks are good in that we have a lot and they're easy to cross-date. There were a few minor species that we wanted to sample in order to have enough for chronologies. We don't want to over-sample ash.

## Questions:
1. Ryan, how many trees would you expect you/we could get done?
2. Thoughts on the ranking criteria?

**Comment by RHelcoski** [comment]
1) Depending on how fast we work and for how long between 8 - 20 trees. Less if the increment corers need to be cleaned and sharpened and more if the trees decide to work with us. I'm willing to get there at daybreak and stay late (if permitted). 

2) I think the criteria is excellent, but it looks like we shifted priorities since last year when we went after oaks and minor species only (along with some Fraxinus... which was actually a lot of Fraxinus). I'm fine with this since I understand why we're prioritizing the dendros. I think switch 3 and 4 though. So we'd get all trees with bands, and all over 50cm (ideally) and then as many oaks and minors that we can. I doubt we'd have time to get some random smaller trees.

PS - I am 100% willing to volunteer to finish coring later in the month depending on how much we get done. I really want to continue the tradition of sampling the oaks and ideally building a few more species specific chronologies.

**Comment by teixeirak** [comment]
1- You're welcome to go any time (days or times). I just need to put in the gate access request ahead of time.

2- Regarding the criteria, it's tricky to say what's best, as that would always depend on the specific question/ analysis. It does bother me that we haven't had a consistent design across years. I like building up oak chronologies (while trying to get enough to build chronologies for minor species), and that's justified in that they're quite abundant in the plot, but also wonder if we should be sampling more in proportion to representation in the plot.  I'll keep thinking about this for a bit.  The next step is to get a list of what died this year (see next comment).

**Comment by teixeirak** [comment]
@ValentineHerr , to plan tree coring (this Saturday), we'll need a list of trees that died this year. Could you please make that a fairly high priority? (Hopefully there won't be too many data issues to clean up. For this, we only need trees >10cm DBH, which should be easier.)

**Comment by ValentineHerr** [comment]
working on this now. Status are quite inconsistent across censuses.... I think I am going to use 2020 status to find the ones that were alive and now dead, but I'll add the 2018 status in the spreadsheet so that you can see that some of them were considered dead in 2018....

**Comment by ValentineHerr** [comment]
I added [this file.](https://github.com/SCBI-ForestGEO/SCBImortality/blob/b826b8be65e2dfefd649c7d7b14fd787ef670b1e/data/list_trees_to_core_temporary_file.csv) called it "temporary" as I am assuming you want to move it to another repo?

I hope I did this right and that you won't run into too many cases where the tree is long gone or something like that related to the issues we see with statuses.

I added a few columns at the end to help you prioritize:
- 0/1 tree has a dendroband,
- 0/1 tree >50cm, 
- 0/1 tree is an oak
- 0/1 tree is none of the above but was randomly selected (I asked for ~10 of them).

Let me know if that works or if you need anything else.

**Comment by ValentineHerr** [comment]
Might be a good idea to check that none of these trees were already cored (especially the ones that were said to be dead in 2018). I can check later.

**Comment by teixeirak** [comment]
Thanks @ValentineHerr , this is very helpful! 

Wow, it's disturbing how many of these went from dead in the 2018 census to live in 2020. Could you please create a file with the status from each year so that we can try to figure out what's going on, and get more context?

**Comment by teixeirak** [comment]
It seems clear that we'll need to adjust the criteria. There are 32 that had dendrobands, so that alone would take a day.

**Comment by ValentineHerr** [comment]
@teixeirak, I added status history in the file

**Comment by ValentineHerr** [comment]
Hmmm... I added a column that looks at if the tree was cored dead, according to [this file](https://github.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/blob/master/tree_cores/list_cored_trees.csv). It is not pretty, there are 72 of them!

...

**Comment by ValentineHerr** [comment]
going to do the same thing but taking the raw data, to see if that improved things... hoping that maybe the script that generates the "clean" data does something wrong and/or that some of the issues that it fixes were not fixed in main census data (used to generate list of trees to visit this year).

**Comment by ValentineHerr** [comment]
I had mismatched a few rows, n cored trees is lower but still 50... all of them say that they were alive in 2016-2017, which is when they were cored and they were supposed to be cored dead.

Trying to look at raw data now to see if that looks better

**Comment by ValentineHerr** [comment]
All right... when I look at the raw data, there are fewer issues (I updated the file) and none of the trees were previously cored. 

I am really not sure what is going on.... One more reason to rewrite the old script "cleaning" script from scratch.

**Comment by teixeirak** [comment]
Thanks, @ValentineHerr ! This is very useful. I'm going to keep this issue open for planning trees to core, but also open a couple new issues of things we'll want to work on later (sometime ahead of the next mort census, but not urgent).

**Comment by teixeirak** [comment]
Returning to the ranking criteria, now with some data (*not complete-- will return*:


## Ranking criteria
1. any trees with dendro bands 
** There are 16**:
<img width="459" alt="image" src="https://user-images.githubusercontent.com/6355854/132579402-a202907f-cf86-44c9-b9b0-bde359bbe818.png">
I think all of these will be worth getting.

2. any tree above 50? cm DBH 
3. random sampling of smaller trees
4. by species: oaks are good in that we have a lot and they're easy to cross-date. There were a few minor species that we wanted to sample in order to have enough for chronologies. We don't want to over-sample ash.

**Comment by teixeirak** [comment]
There's also the endangered Juglans cinera, where 1 of 2 remaining individuals died...

**Comment by RHelcoski** [comment]
I agree that CECA and COFL are good to target. I'd like to get the Juglans too! Sad that it's down to a single individual now. There's no way we can build a chronology of it, but the fact that it's an endangered species makes me feel like we should catalog it.

I also agree the additional FRAM are unnecessary for chronologies. Their only use as I can tell would be if you have something specific in mind comparing band to core and FRAM in particular. Depending on what you're thinking I can put them on a lower priority or just cut them out.

**Comment by teixeirak** [comment]
The trees with dendro bands would be particularly helpful for @rudeboybert 's Baysian data fusion project, although I doubt we could get them analyzed in time. However, I think they're likely too be helpful in the future, so I'd still place high priority on those.

**Comment by RHelcoski** [comment]
got it. Also mad respect to @rudeboybert. I didn't realize there was a fellow rudy in the lab!

**Comment by teixeirak** [comment]
@RHelcoski or @jenajordan , where are you keeping the record of trees cored?

**Comment by jenajordan** [comment]
@RHelcoski  and @teixeirak - I have a map and notes of trees cored. Should I post the list/ record here?

**Comment by RHelcoski** [comment]
just the list is fine and you already posted that here [https://github.com/SCBI-ForestGEO/SCBImortality/issues/60#issuecomment-918426044](url) so that's fine.

**Comment by teixeirak** [comment]
@jenajordan , just looking at old issues. Have you posted those notes?

**Comment by teixeirak** [comment]
Jen provided the file via email, and I have loaded it here: https://github.com/SCBI-ForestGEO/TreeRings/commit/9646bd4d8170b0eaa98c9320b69d50766cfd7a86#diff-bd5a7dbd71a58dcf976042bbdc461f514fa11e4b0720a38ab701b18f460bf497
