### ISSUE TITLE
finalizing 2021 data

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#51]
@briannakcalkins , @jenajordan , @trogers4, @mageeluke , @ValentineHerr, @rudeboybert , @jess-shue -- We've officially completed the SCBI census and resolved all errors!! Thank you all for your help!

<img width="738" alt="image" src="https://user-images.githubusercontent.com/6355854/130608141-89a228b1-e4d0-4411-a9c0-ece8aa3afdf4.png">

The other nice piece of news is that the field fix error rate went down quite a bit after we implemented the continuous integration system. This is good news, and will strengthen @rudeboybert's (our) paper.

<img width="856" alt="image" src="https://user-images.githubusercontent.com/6355854/130608604-f00966e0-ecd6-42a3-932c-2b9b36c33fe5.png">

---- 

The data tests still fail, though. @ValentineHerr , I believe there was some trick to this, which @rudeboybert figured out for Harvard Forest. Let's get that figured out here.

**Comment by rudeboybert** [comment]
Hooray!

Yes, the fix was that when no new errors are found, you need to delete the existing error reports as seen here https://github.com/SCBI-ForestGEO/HarvardMortality/commit/1fb9071545634f96a5622a32ff78192fddadcf1d

The GitHub Actions ❌ vs ✅ is based on the presence of the error reports.

**Comment by ValentineHerr** [comment]
> The data tests still fail, though. @ValentineHerr , I believe there was some trick to this, which @rudeboybert figured out for Harvard Forest. Let's get that figured out here.

I fix the issues and we passed the test!!! Hooray! (Thanks @rudeboybert for pointing out the error)

Congrats everybody.

**Comment by teixeirak** [comment]
Thank you all so much for your contributions!

**Comment by jess-shue** [comment]
Great job on completing the survey!
