### ISSUE TITLE
suspicious DBHs warning

### ISSUE THREAD

**Issue by ValentineHerr** [SCBI-ForestGEO/SCBImortality#55]
I created [this file](https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/temporary_files_for_QA_QC/dbh_history_DBH_dead_suspicious.csv) to review suspicious DBH warnings.

**Comment by teixeirak** [comment]
If we can get a list of suspicious trees to revisit, @jenajordan  is out there today and would likely have time to double check some.

**Comment by teixeirak** [comment]
I think it's too late to go back and field-check these now. 

@ValentineHerr , for the upcoming season, can we switch suspicious DBH from a warning to an error?
