### ISSUE TITLE
mapping column names across years

### ISSUE THREAD

**Issue by ValentineHerr** [SCBI-ForestGEO/SCBImortality#56]
Trying to unify columns across years. @teixeirak, I may need help with this as I believe protocoles have changed over the years and I am not familiar with all columns names... (Mainly I am not always sure when a column is fraxinus-related only or not, and don't know some of the abbreviations).

First column is the columns as they appear in any year, 2014-2021 is saying what year each column name appear in, and last column is me trying to give the same name to columns that mean the same thing.

Feel free to edit, but let me know when you do so.
 

column name | 2014 | 2015 | 2016 | 2017 | 2018 | 2019 | 2020 | 2021 | unified colum name | coded_in_1A | coded_in_1B
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
as | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | delete |   |  
canker..swelling..deformity | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | canker.swelling.deformity |   |  
code.2013 | 1 | 1 | 1 | 1 | 1 | 0 | 0 | 0 | code.2013 |   |  
code.2018 | 0 | 0 | 0 | 0 | 0 | 1 | 1 | 0 | code.2018 |   |  
comments | 1 | 1 | 1 | 1 | 0 | 0 | 0 | 0 | notes | 1 | NA
cored | 0 | 0 | 0 | 0 | 1 | 1 | 1 | 0 | cored |   |  
crown.position | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | crown.position |   |  
crown.position...10.cm.dbh | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | **?** |   |  
crown.thinning | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | **?** |   |  
d.shaped.exit.hole.count | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | d.shaped.exit.hole.count |   |  
date | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | date |   |  
dbh | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | dbh.2018 |   |  
dbh.2013 | 1 | 1 | 1 | 1 | 1 | 0 | 0 | 0 | dbh.2013 |   |  
dbh.2018 | 0 | 0 | 0 | 0 | 0 | 1 | 1 | 0 | dbh.2018 |   |  
dbh.if.dead | 0 | 1 | 1 | 1 | 1 | 1 | 1 | 0 | dbh.if.dead |   |  
de | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | delete |   |  
de.count | 0 | 0 | 1 | 1 | 1 | 1 | 1 | 0 | d.shaped.exit.hole.count |   | NA
dead.crown.position | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | crown.position**?** |   |  
dead.dbh | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | dbh.if.dead |   |  
df | 0 | 0 | 0 | 1 | 1 | 1 | 1 | 0 | delete |   |  
dwr | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | dwr |   |  
eabf | 0 | 0 | 1 | 1 | 1 | 1 | 1 | 1 | eabf |   |  
epicormic.growth | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | fraxinus.epicormic.growth |   |  
fad | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | fad |   |  
fad.1 | 1 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | **?** |   |  
fad.2 | 1 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | **?** |   |  
fad.3 | 1 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | **?** |   |  
fad.4 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | **?** |   |  
fad1 | 0 | 0 | 1 | 1 | 1 | 1 | 1 | 0 | **?** |   |  
fad2 | 0 | 0 | 1 | 1 | 1 | 1 | 1 | 0 | **?** |   |  
fad3 | 0 | 0 | 1 | 1 | 1 | 1 | 1 | 0 | **?** |   |  
fad4 | 0 | 0 | 1 | 1 | 1 | 1 | 1 | 0 | **?** |   |  
fraxinus.crown.thinning | 0 | 0 | 1 | 1 | 1 | 1 | 1 | 0 | fraxinus.crown.thinning |   |  
fraxinus.epicormic.growth | 0 | 0 | 1 | 1 | 1 | 1 | 1 | 0 | fraxinus.epicormic.growth |   |  
hom | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | delete | NA | 1
lean.angle.if.greater.than.15.degrees | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | lean.angle.if.greater.than.15.degrees |   |  
liana.load | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 0 | liana.load | NA | NA
lianas | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | liana.load **same scale?** | NA | 1
lx | 0 | 1 | 1 | 1 | 1 | 1 | 1 | 0 | lx |   |  
ly | 0 | 1 | 1 | 1 | 1 | 1 | 1 | 0 | ly |   |  
new.condition | 1 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | will be change to status.year | 1 |  
new.status | 0 | 0 | 1 | 1 | 1 | 1 | 1 | 0 | will be change to status.year | 1 |  
notes.2021 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | notes | NA | 1
old.comments | 0 | 0 | 0 | 0 | 1 | 1 | 1 | 0 | delete | 1 | NA
perc.crown | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 0 | **?** |   |  
percentage.of.crown.intact | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | **?** |   |  
percentage.of.crown.living | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | **?** |   |  
previous.condition | 1 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | will be change to status.year-1 | 1 | NA
quad | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | quadrat | NA | 1
quadrat | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 0 | quadrat | NA | NA
qx | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | delete | NA | 1
qy | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | delete | NA | 1
rotting.trunk | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | rotting.trunk |   |  
sp | 0 | 0 | 1 | 1 | 1 | 0 | 0 | 0 | sp | NA | NA
species | 1 | 1 | 0 | 0 | 0 | 1 | 1 | 1 | sp | 1 | 1
ss | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | delete |   |  
status..2017 | 0 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | status.2017 |   |  
status.2014 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | status.2014 |   |  
status.2015 | 0 | 0 | 1 | 1 | 1 | 1 | 1 | 0 | status.2015 |   |  
status.2016 | 0 | 0 | 0 | 1 | 1 | 1 | 1 | 0 | status.2016 |   |  
status.2017 | 0 | 0 | 0 | 0 | 0 | 1 | 1 | 0 | status.2017 |   |  
status.2018 | 0 | 0 | 0 | 0 | 0 | 1 | 1 | 1 | status.2018 |   |  
status.2019 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | 0 | status.2019 |   |  
status.2021 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | status.2021 |   |  
stem | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 0 | stemtag | 1 | NA
stemtag | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | stemtag | NA | NA
submission.id | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | submission.id |   |  
surveyor | 0 | 0 | 0 | 0 | 0 | 1 | 1 | 0 | surveyor | NA | NA
surveyorid | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | surveyor | NA | 1
surveyors | 1 | 1 | 1 | 1 | 1 | 0 | 0 | 0 | surveyor | 1 | NA
tag | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | tag | NA | NA
vb | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | delete |   |  
w | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | delete |   |  
wounded.main.stem | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | wounded.main.stem |   |  
x2018.comments | 0 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | notes | 1 | NA
x2019.comments | 0 | 0 | 0 | 0 | 0 | 1 | 1 | 0 | notes | 1 | NA
x2020.comments | 0 | 0 | 0 | 0 | 0 | 0 | 1 | 0 | notes | 1 | NA

**Comment by ValentineHerr** [comment]
@teixeirak, 
I am assuming` liana.load` and `liana ` is the same measure accross surveys.
FYI, the max liana load is as follow for each year:
![image](https://user-images.githubusercontent.com/19673377/131683597-fff71475-bdf9-4cb1-8d48-e5e53152c8f7.png)

**Comment by teixeirak** [comment]
correct.

**Comment by ValentineHerr** [comment]
thinking about spliting `EABF` into individual columns like in 2017 (e.g. column `de` is filled with "DE"), could still leave EABF column with "DE,W" etc...

**Comment by ValentineHerr** [comment]
fad is very inconsistent too... sometimes in separate columns, sometimes in only one... I think I'll keep only one fad column... as there is a lit more options than for EABF...

options that exist in data set:
![image](https://user-images.githubusercontent.com/19673377/131688456-69aaa7cc-3418-4d4d-bd4d-b3cd4986ae2a.png)

**Comment by ValentineHerr** [comment]
closing this and I'll start a new, cleaner, issue.
