### ISSUE TITLE
standardaizing EABF columns

### ISSUE THREAD

**Issue by ValentineHerr** [SCBI-ForestGEO/SCBImortality#57]
EABF column is not consistent across years. Sometimes factors are separated by `,`, sometimes `;`, sometimes `,space `, etc...
also, in 2017, each factor got its own column.

- [ ] keep `EABF` but standardize it
- [ ] delete indifidual columns in 2017 (after making sure they match what is in `EABF`

this are all the types of EABF that exist in the database:  "none" "SS"   ""     "AS"   NA     "VB"   "W"    "DE"   "DE."  "w"    "None"
- [ ] check list is complete

**Comment by ValentineHerr** [comment]
note: EABF was recorded only starting 2016.

**Comment by ValentineHerr** [comment]
note: "W" is in EABF and FAD but they mean different things

I think I should keep only one column for EABF, delete the individual columns in 2017. if the one column is cleaned up and standardized, it would be easy to split if someone needed to.

**Comment by teixeirak** [comment]
This all sounds good. Thanks for working on it!

**Comment by ValentineHerr** [comment]
In 2017, all individual EABF columns match with the one EABF column except for 2 trees that have a value in `DE` but `DE` it is not mentioned in `EABF`... one has some DE.count... but most importantly, neither are ash trees.... unless caca was misidentified...

quadrat|tag|sp|new.status|eabf|de|de.count|comments|surveyors
--|--|--|--|--|--|--|--|--
613|60552|caca|DS||DE|21|did not senescence|Helcoski
1914|190807|quve|DS||DE|NA||Helcoski/Prestipino/Anderson-Teixeira

I think I'll leave it for now but then have some code that empties EAFB-related columns (here `de.count`) if not ash or Chionanthus

**Comment by ValentineHerr** [comment]
I am a bit confused with column `DF` in surveys 2017-2019, and in general with the "DF" code.

looking at 2019 protocole (but it is also in latest protocole), entering "DF" in `fad` means "complete defoliation", but the protocole also says to record crown condition using scale 1-5 (which I understand a crown thinning index, entered in `DF` column). Scale goes from 1-healthy with no defoliation to 5-dead tree with no leaves in canopy (excluding epicormic growth) .

Issues I have with the protocole (which I understand is maybe coming from an old one):
1. why say "complete defoliation" if it is to ask a code from healthy to dead?
2. why say 5 is dead if in fact the tree is potentially not dead (with epicormics)
3. value 1 should not say "healthy"... there could be other issues than defoliation that make a tree unhealthy
it is wording but wording matters... 

Issues I have with the data:
- why don't all trees have a 1 in `DF` if there is nothing wrong with them?
- there are trees with "DF" in fad but no value in column `DF`(at least in 2019)
- there are trees with "DF" in fad but a value <5 (sometimes even 1) in column `DF` (at least in 2019)... meaning they still have leaves so how could defoliation be associated to death? or maybe i am mistaken when I think "FAD" stands for "Factor associated to Death"?
- for ash trees,  why aren't the values in "DF" the same as in `fraxinus.crown.thinning` ? (at least in 2019.)

I know a lot of this as been thought better for 2021 protocole but there is a lot of cleaning to be done in previous years... (and the protocole stays ambiguous... maybe some of those old tables for the codes should be updated.)

**Comment by ValentineHerr** [comment]
@teixeirak, in 2021 data, what is the difference between `Crown position`  and `Crown position < 10 cm DBH` ?

I understand that  `Crown position < 10 cm DBH`  is for Fraxinus, but what is about  " < 10 cm DBH"?  I see plenty of trees that are >10cm that have a value in it. I also see a lot of small fraxinus with no value there.


Would  `Crown exposure` be a better name for `Crown position` ?

**Comment by teixeirak** [comment]
`Crown position <10 cm` is the same as `crown position`; it was simply entered separately in FastField because of the way the form populates, I believe... Both should only be collected for dead trees.

Here's what we have in the metadata: 
<img width="899" alt="image" src="https://user-images.githubusercontent.com/6355854/131888199-6728bea8-ab2b-40f5-88cc-8b15368cc188.png">

**Comment by teixeirak** [comment]
> Issues I have with the protocole (which I understand is maybe coming from an old one):
> 
>     1. why say "complete defoliation" if it is to ask a code from healthy to dead?
> 
>     2. why say 5 is dead if in fact the tree is potentially not dead (with epicormics)
> 
>     3. value 1 should not say "healthy"... there could be other issues than defoliation that make a tree unhealthy
>        it is wording but wording matters...

You're right, and this may have caused some past confusion (I'm pretty sure we discussed this in an issue, but can't find it at the moment).  To solve this, I edited this in the protocol (now titled 2022 protocol).

**Comment by teixeirak** [comment]
> Issues I have with the data:
> 
>     * why don't all trees have a 1 in `DF` if there is nothing wrong with them?

** You mean all ash? It should be recorded for all ash, so any missing are missing data. An analysis could probably assume they are 1's, but we won't do that in the master data.**
> 
>     * there are trees with "DF" in fad but no value in column `DF`(at least in 2019)

**Missing data.**
> 
>     * there are trees with "DF" in fad but a value <5 (sometimes even 1) in column `DF` (at least in 2019)... meaning they still have leaves so how could defoliation be associated to death? or maybe i am mistaken when I think "FAD" stands for "Factor associated to Death"?

**Correct that FAD stands for Factor Associated with Death, but we also record it for AU trees. So this is okay. But DF in FAD + DF=1 is inconsistent.**
> 
>     * for ash trees,  why aren't the values in "DF" the same as in `fraxinus.crown.thinning` ? (at least in 2019.)

**Ack, I've been thinking all along `DF` = `fraxinus.crown.thinning`. So responses above might not make sense. So what is `DF`?**

**Comment by teixeirak** [comment]
Also note: we discussed the problem of "dead" trees with epicormics here: https://github.com/SCBI-ForestGEO/SCBImortality/issues/8.

**Comment by ValentineHerr** [comment]
> Ack, I've been thinking all along `DF` = `fraxinus.crown.thinning`. So responses above might not make sense. So what is `DF`?

I do not know what DF is and how to reconcile it with `fraxinus.crown.thinning`.

`fraxinus.crown.thinning` started in 2016. `DF` in 2017.

**Comment by teixeirak** [comment]
My notes on trying to figure out what `DF` is:
- number 1-5, or NA
- it is NOT limited to *Fraxinus*
- recorded for minority of trees, but NOT limited to dead trees. Most trees for which it's recorded are dead or AU (and maybe the records for A's are just errors...?)

AHA!  -- I believe it is a rating of defoliation :
<img width="666" alt="image" src="https://user-images.githubusercontent.com/6355854/149409706-52e62449-cbb7-42e8-9d0b-129dfab818bc.png">

**Comment by teixeirak** [comment]
So, this would be for trees with some level of defoliation. It would be rated oon the Smith/Flower 2013 scale-- same as Fraxinus: 

<img width="870" alt="image" src="https://user-images.githubusercontent.com/6355854/149410085-bbb38fe0-ec21-4947-9ba7-778174601146.png">

**Comment by ValentineHerr** [comment]
it is weird that 2017-2020 have both columns (`DF` and `fraxinus.crown.thinning`).

**Comment by teixeirak** [comment]
I think that's because `DF` applies to any species that is AU, whereas `fraxinus.crown.thinning` applies only to (all) Fraxinus. But you're right that it's a funny setup.

**Comment by ValentineHerr** [comment]
Closing this now. the translation of the various variables of each year can be found [here](https://github.com/SCBI-ForestGEO/SCBImortality/blob/df08e9a47ab6518cbd541d81182e745f45541ac8/raw_data/standardizing_colnames.csv).
Things do not align perfectly but it will be dealt with when it is needed.
