### ISSUE TITLE
add error/ warning for incorrect / unlikely status code

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#58]
@ValentineHerr , in the 2021 census, we had a number of cases where "PD" was selected as the status code for trees that were never previously coded as dead (see [this file](https://github.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/blob/master/tree_cores/list_cored_trees.csv)). For future censuses, this should be flagged as an error (or better yet, not allowed in FastField, if that's possible, @jess-shue ).

**Comment by teixeirak** [comment]
I broadened the title of this issue because it would be valuable to apply this in other cases. We already generate warnings for dead trees come back to life, but there are other cases.

Errors:
- PD when it was previously alive
- PD when it was previously DS (in this case we want DS or DC)

Warnings:
- dead tree come back to life (already have this)
- DC --> DS (think we already have this)

**Comment by jess-shue** [comment]
@teixeirak @ValentineHerr  The 'PD' code was included because it is an option in your previous mortality data 'status' column. It can certainly be removed from FFF's for this new version of the mortality census. I've deleted it and updated the form.

**Comment by teixeirak** [comment]
Thanks, @jess-shue . 

@ValentineHerr , we don't need the PD tests mentioned above.
