### ISSUE TITLE
Trees marked dead found live when coring

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#60]
@RHelcoski  reports:  There were several trees that were marked dead but were alive, including all of the Sassafras. The trees were all damaged in some way (break @ 10m, on ground, etc), but they were also very, very, clearly alive. 

@RHelcoski or @jenajordan , do you have a record of these trees?

**Comment by jenajordan** [comment]
@RHelcoski and @teixeirak - I can list all the trees we visited, whether we could core or not, whether alive or not. I could either just type a list here or upload a spreadsheet in csv format? If there's a template I should use, let me know (otherwise I'll just label columns with quad, tag #, species, and notes). Still getting used to how to use GitHub.

**Comment by jenajordan** [comment]
[tree coring 9:11:21.csv](https://github.com/SCBI-ForestGEO/SCBImortality/files/7156498/tree.coring.9.11.21.csv)

**Comment by jenajordan** [comment]
[tree coring 9:11:21.csv](https://github.com/SCBI-ForestGEO/SCBImortality/files/7156528/tree.coring.9.11.21.csv)

This is current list.

**Comment by teixeirak** [comment]
> [tree coring 9:11:21.csv](https://github.com/SCBI-ForestGEO/SCBImortality/files/7156528/tree.coring.9.11.21.csv)
> 
> @RHelcoski and @teixeirak - This is current list of cored trees

The updated version is here: https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/raw_data/tree_coring_2021.csv.

**Comment by teixeirak** [comment]
@ValentineHerr , what would be the best procedure for dealing with the trees marked dead that were found alive when coring? There's just a handful, so fixes could be manual.

**Comment by ValentineHerr** [comment]
best would be to add a line in [this file](https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/raw_data/manual_fixes.csv)

**Comment by RHelcoski** [comment]
It would appear we're missing some trees, but I think this is just because @jenajordan has just not yet updated it with the trees she finished on her own. Jen, can you confirm? Check @teixeirak 's list above.

**Comment by ValentineHerr** [comment]
lean.angle for 60024 is already 90.

I added the appropriate code in the file.
Technically, I believe we should also change the values in columns that are filled when tree is found dead like "dbh.if.dead" etc...  but maybe it does not hurt to let them unchanged....

**Comment by teixeirak** [comment]
Thanks so much! We can close this now.
