### ISSUE TITLE
improving written protocol for 2022

### ISSUE THREAD

**Issue by ValentineHerr** [SCBI-ForestGEO/SCBImortality#62]
@teixeirak,

Here is a couple things that would be good to address in the new protocole (feel free to disagree):

- [x]  protocol says `If the status is “AU”, ... record crown position` but the section describing how to rank crown position says `Crown Position (dead trees only)` --*> change to `Crown Position (dead and unhealthy trees only)` 
- [x] the protocole does not say to measure the DBH when tree is dead--> add that in the list of things to do in this case + change section `Diameter at breast height (DBH; mm)` to `Diameter at breast height (DBH; mm) (dead trees only)`
- [x] filling `DWR` (dead with resprout) is not mentioned in the protocol. 
- [x] also, aren't we calling a tree AU if is has resprout? if yes, the name of the column should be changed to `resprout` (note that SS in EABF is "Stump sprouts")

- [x] In 2021, there is 3 types of crown positions:
 - Crown.position
 - Dead.crown.position
 - Crown.position...10.cm.DBH

you said [here](https://github.com/SCBI-ForestGEO/SCBImortality/issues/57#issuecomment-911896091) that `Crown position <10 cm` is the same as `crown position`. But they don't seem to match exactly (see bellow, number of cases with the different combinations of those 3 columns), and `Crown.position` actually seems to be `Crown illumination` (see figure 1 in protocole).
Also it is surprising that `Crown.position...10.cm.DBH` and `Dead.crown.position`, which seem to use the same system, don't always match (see when Crown.position...10.cm.DBH = S or NA).... I think crown position should only be asked once, whether the tree is dead or alive. And if you do want crown illumination, it should be called that.

```
, , Crown.position...10.cm.DBH = CD

              Dead.crown.position
Crown.position   CD    D    I   OG    S <NA>
          1       0    0    0    0    0    0
          2       0    0    0    0    0    1
          3       7    0    0    0    0    7
          4       1    0    0    0    0    2
          5       0    0    0    0    0    0
          <NA>    0    0    0    0    0    0

, , Crown.position...10.cm.DBH = D

              Dead.crown.position
Crown.position   CD    D    I   OG    S <NA>
          1       0    0    0    0    0    0
          2       0    0    0    0    0    0
          3       0    0    0    0    0    0
          4       0    1    0    0    0    2
          5       0    0    0    0    0    0
          <NA>    0    0    0    0    0    0

, , Crown.position...10.cm.DBH = I

              Dead.crown.position
Crown.position   CD    D    I   OG    S <NA>
          1       0    0    1    0    0    0
          2       0    0    5    0    0   40
          3       0    0    2    0    0    9
          4       0    0    0    0    0    0
          5       0    0    0    0    0    0
          <NA>    0    0    0    0    0    0

, , Crown.position...10.cm.DBH = OG

              Dead.crown.position
Crown.position   CD    D    I   OG    S <NA>
          1       0    0    0    0    0    0
          2       0    0    0    0    0    0
          3       0    0    0    1    0    0
          4       0    0    0    0    0    0
          5       0    0    0    0    0    0
          <NA>    0    0    0    0    0    0

, , Crown.position...10.cm.DBH = S

              Dead.crown.position
Crown.position   CD    D    I   OG    S <NA>
          1       0    0    2    0  103  252
          2       0    0    4    0    1   13
          3       3    0    0    0    0    2
          4       0    0    0    0    0    0
          5       0    0    0    0    0    0
          <NA>    0    0    0    0    0    1

, , Crown.position...10.cm.DBH = NA

              Dead.crown.position
Crown.position   CD    D    I   OG    S <NA>
          1       4    0    4    0  150 3079
          2       1    0   62    0    5 1847
          3      90    3    6    0    1 2192
          4       5   28    0    0    1  490
          5       0    0    0    0    0    2
          <NA>    1    0    1    0    2   34
```

**Comment by ValentineHerr** [comment]
-[ ]  need a figure number for `Crown Assessment` figure

**Comment by ValentineHerr** [comment]
other quick question:

@teixeirak , prior to 2021, only `perc.crown`​ was recorded. Does it correspond to 2021's ​`percentage.of.crown.intact`​ or ​`percentage.of.crown.living`​ ? 

I find it a little redundant/confusing with `crown.thinning` (which is only for fraxinus)... but the protocole might be clear enough about the distinction - although I would rename the name of the figure for "Crown Assessment" (which need a figure number, see comment above) to something like "assessing percent crown intact and percent crown living" so there is no possible confusion.

**Comment by teixeirak** [comment]
`crown.thinning` is this:
<img width="331" alt="image" src="https://user-images.githubusercontent.com/6355854/149421299-fe68d996-fad2-41b7-b88a-fd011737ef46.png">

**Comment by teixeirak** [comment]
So, crown.thinning is not the same as either `percentage.of.crown.intact`​ or ​`percentage.of.crown.living`​ , but it could be compared to `percentage.of.crown.intact`​ if that continuous variable were transformed into these categories.

**Comment by ValentineHerr** [comment]
Looking into this more. in 2017-2020, there are 3 columns that are on this same scale (1-5)...:

- `perc.corwn`
- `DF`
- `fraxinus.crown.thinning`

`perc.crown` and `DF` are often not recorded together on the same tree (it is often one or the other that got recorded). When they are both recorded, they do not match.


![image](https://user-images.githubusercontent.com/19673377/149533126-22a7b282-2a24-4926-aa0e-aa271486ff4a.png)



(copying this message to this issue #57)

**Comment by ValentineHerr** [comment]
@teixeirak,  [This file](https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/raw_data/trying_to_understand_perc.crown_DF_fraxinus.crown.thinning.csv) shows all the existing combinations of the three columns we are trying to make sense of.

- `perc.crown` seems to be recorded mostly for dead trees (but a few A and AU trees got a record too), and for all species, including fraxinus
- `DF` seems to be recorded mostly for AU trees (but some dead, and previously dead, and A trees got a record too), and for all species, including fraxinus
- `fraxinus.crown.thinning` seems to be recorded for any status, mostly for fraxinus but a few other species got it too... (likely some carya but I have not checked).

**Comment by teixeirak** [comment]
`perc.crown` refers to percent crown (wood) intact (analagous to `percentage.of.crown.intact`):
<img width="544" alt="image" src="https://user-images.githubusercontent.com/6355854/149536100-2cc26bba-9a11-4e1e-a6d2-8e72b79ea20f.png">

`DF` refers to defoliation (analagous to `percentage.of.crown.living`)

`fraxinus.crown.thinning` refers to defoliation for Fraxinus + CHIVI (also affected by EAB). It should be recorded for all individuals. It uses the same scale as `DF`, so these should match if ever recorded for the same individual.

**Comment by ValentineHerr** [comment]
ok, thanks.

`fraxinus.crown.thinning` and `DF` do not always match when recorded on the same individual. But I'll ignore that for now.

**Comment by ValentineHerr** [comment]
to try to match 2021 and future censuses, I'll translate DF (percentage.of.crown.living) and prec.crown (percentage.of.crown.intact) to percentages, (taking average of 1-5 score).

okay?

**Comment by teixeirak** [comment]
> to try to match 2021 and future censuses, I'll translate DF (percentage.of.crown.living) and prec.crown (percentage.of.crown.intact) to percentages, (taking average of 1-5 score).
> 
> okay?

That's modifying and potentially biasing the data, and I wouldn't be comfortable putting that into an analysis without explicitly stating that. In an analysis comparing them, it would be better too put the newer data into categorical classes (although we don't want to throw out the higher precision for other uses).

If it greatly facilitates working with the data, we could take the midpoint of each category and state in the  metadata that it is an average.

**Comment by ValentineHerr** [comment]
- [ ] in 2021 there are quite a few notes saying "epicormic branches", but nothing is entered in `epicormic.growth` as that column is reserved for fraxinus. Maybe it would be worth opening that column to all speices, like it is the case for `canaker...` or `wound` or `rotting trunk` ?

**Comment by ValentineHerr** [comment]
> > to try to match 2021 and future censuses, I'll translate DF (percentage.of.crown.living) and prec.crown (percentage.of.crown.intact) to percentages, (taking average of 1-5 score).
> > okay?
> 
> That's modifying and potentially biasing the data, and I wouldn't be comfortable putting that into an analysis without explicitly stating that. In an analysis comparing them, it would be better too put the newer data into categorical classes (although we don't want to throw out the higher precision for other uses).
> 
> If it greatly facilitates working with the data, we could take the midpoint of each category and state in the metadata that it is an average.

I meant mid point. Ok, I'll put newer data into category,, changing name to be more explicit lie `score.crown.intact`, and keeping the `percentage.of.crown.intact`

**Comment by teixeirak** [comment]
> you said [here](https://github.com/SCBI-ForestGEO/SCBImortality/issues/57#issuecomment-911896091) that `Crown position <10 cm` is the same as `crown position`.

@ValentineHerr , I made a mistake there (sorry!). These names are confusing. `Crown Position` is used in the FastField app to describe crown illumination index, and `Dead Crown Position` to describe what I've been calling `crown position`. So `Crown position <10 cm` is actually `Dead crown position`.

**Comment by teixeirak** [comment]
> * also, aren't we calling a tree AU if is has resprout? if yes, the name of the column should be changed to `resprout` (note that SS in EABF is "Stump sprouts")

Good question. I believe it counts as dead, although I think there might also be a special code for this. Leave as is for now.

**Comment by ValentineHerr** [comment]
> So `Crown position <10 cm` is actually `Dead crown position`.

@teixeirak, what about `Dead.crown.position` then?

See [this file](https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/raw_data/standardizing_colnames.csv) (relevant rows in screenshot below) to see how the columns are currently interepreted.

![image](https://user-images.githubusercontent.com/19673377/169046722-9935810d-ac38-4e71-9500-9d380216c324.png)
![image](https://user-images.githubusercontent.com/19673377/169047406-84bdc355-cd4d-4777-b8b7-aa5a51e907b2.png)

**Comment by teixeirak** [comment]
> @teixeirak, what about `Dead.crown.position` then?

That would be `crown_position` (same as `Crown.position...10.cm.DBH`)

And yikes... we have a crazy mix of variable names!

**Comment by teixeirak** [comment]
I think we can close this now.
