### ISSUE TITLE
create a guide to pests and pathogens

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#64]
It would be good to have a student create an updated field guide to the pests & pathogens likely to appear in the plot. This could be based on existing guide(s) in this repo, review of VA dept of forestry reports, and literature/ web search.

**Comment by teixeirak** [comment]
# Desired output
We want an .Rmd that produces a .pdf guide that can be used digitally or printed. It should be convenient for use in the field.

## Outline
1.  matrix of species x pests/pathogens for convenient reference as to which pests/pathogens may be affecting a certain tree species
2. table of contents for pests/pathogens
3. individual pages for each pests/pathogen, including info (see below) and photos
4. references

## Desired info for each pest/pathogen

- pest_pathogen_common_name 
- pest_pathogen_scientific_name 
- tree_species_affected 
- origin (native, exotic, cosmopolitan, undertermined)
- pathogen_type (insect, fungus, etc)
- part of tree affected and mechanism of damage (e.g., stem rot, xylem disruption, leaf herbivory)
- symptoms: specific symptoms that help ID the pest/pathogen. Include photos if available.
- status at SCBI: notes on any observations at SCBI, including year, how detected, etc.
- citations to info sources (with full list in references section)



# Sources to reference
1. [our list of insects & pathogens at SCBI](https://github.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/tree/master/species_lists/insects_pathogens). Includes many of the fields listed above.
2. https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/doc/Protocols/Visual%20guides/Tree%20Mortality%20Guide_2020.pdf
3. https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/doc/Protocols/Visual%20guides/Pest_pathogen%20watch.docx
4. [Virginia Department of Forestry- Forest Health](https://dof.virginia.gov/forest-management-health/forest-health/)
    - https://dof.virginia.gov/wp-content/uploads/Tree-and-Forest-Health-Guide.pdf

**Comment by teixeirak** [comment]
The Virginia Department of Forestry's [Tree-and-Forest-Health-Guide](https://dof.virginia.gov/wp-content/uploads/Tree-and-Forest-Health-Guide.pdf) (also loaded [here, in this repo](https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/doc/Protocols/Visual%20guides/Tree-and-Forest-Health-Guide.pdf) provides a lot of the information outlined above. We don't want to re-invent the wheel. 

What will be novel and useful is doing this assessment in the context of the data that we've been collecting. We'll want to look at [mortality rates by species](https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/R_results/Barplots_MortalityRates_and_BiomassMortality.tiff) and proportions of unhealthy individuals in each species. Then, we'll want to look at FADs (factors associated with death) recorded for each species and compare these against common mortality agents, particularly for species with lots of disease/ decline. Are we detecting common agents of mortality? Or failing to detect because we don't know what to look for? Or is something else driving mortality? We can then produce a guide that will help field surveyors record appropriate info.

**Comment by teixeirak** [comment]
@irdangler , I'm responding to your questions here so that we preserve the record:

1.	To find the species to focus on, will I be looking at the mortality data to find the trees with the highest mortalities and then finding any FADs associated with that and using those? I assume I should also compare with the VDoF guide and their pests/pathogens, but how do I pick which pests I'd like to focus on?

## part 1: mortality rates (start here)
- Please use [this file](https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/R_results/mortrates_and_agbmort_by_species.csv) to describe mortality rates per species
- I've started a new file to list species of concern: https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/doc/TreeDiseaseGuide/species_of_concern.md. I'll flesh this out with criteria, and then you can classify the species. To edit this, you click the pencil icon in the upper right corner. You can find a basic guide to this type of file [here](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet). It's pretty straightforward.

## part 2: disease rates
- A second step would be to look at rates of disease in still-living trees (AU status), but let's come back to that. 


3.	When I do find the ones I'd like to focus on, should I highlight or bold them in the matrix so it's obvious? Or will there be another location where we can note this?

As above, let's note them [here](https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/doc/TreeDiseaseGuide/species_of_concern.md).

**Comment by teixeirak** [comment]
@irdangler , the criteria for identifying species of concern based on mortality is ready.

**Comment by teixeirak** [comment]
The easiest solution would be to make it so that the merge on l.42 retains the exact same set and order of species. The code will still have weaknesses from my coding shortcuts, but would produce the intended results. 

Ultimately, I'd like to  make this more robust, but for now we just need something that works for Isabella's presentation next week.

**Comment by ValentineHerr** [comment]
looking into this now.
So ideally you'd like would recreate a correctly ordered version of `tree_species_summary` (using the older version of it for now) and then change the code so it pull the new master version of it on line 36?

**Comment by teixeirak** [comment]
That would work. The best practice would be to have all the info (l. 38-40) populated via proper merges, rather than just assuming same order. 

And, ultimately, all the info in tree_species_summary could be coded, and the file generated fresh on each run.

**Comment by teixeirak** [comment]
> That would work. The best practice would be to have all the info (l. 38-40) populated via proper merges, rather than just assuming same order.

If that were done, and the `TDconcern_index` on l.127 were also done this way, the order of the table wouldn't matter.

**Comment by ValentineHerr** [comment]
> That would work. The best practice would be to have all the info (l. 38-40) populated via proper merges, rather than just assuming same order.
> 
> And, ultimately, all the info in tree_species_summary could be coded, and the file generated fresh on each run.

to be generated fresh on each run it might be best to create a file wuth just the IUCN status (and in the species order you want). Then we pull that in and add the other columns to create tree_species_summary  from scratch

**Comment by teixeirak** [comment]
IUCN status is in this file: https://raw.githubusercontent.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/master/species_lists/Tree%20ecology/SCBI_ForestGEO_sp_ecology.csv (read in as "tree_sp_ecology" data frame). The species names are there too, of course. The only unique info in "tree_species_summary" is two fields filled manually by Isabella (mortality.rates and AU.status). Both are codeable, and ultimately we'll want to switch over to that, but not necessary right now unless its easier.

**Comment by teixeirak** [comment]
The criteria for `mortality.rates` and `AU.status` are in [this doc](https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/doc/TreeDiseaseGuide/species_of_concern.md).

**Comment by ValentineHerr** [comment]
How did you make the list of species in the first part of that document?

**Comment by teixeirak** [comment]
I used the list from tree_species_summary, which I had manually copied the list from this file: https://raw.githubusercontent.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/master/species_lists/Tree%20ecology/SCBI_ForestGEO_sp_ecology.csv (read in as "tree_sp_ecology" data frame). Same goes for the matrix.csv file. I then relied on the fact that those lists were identical.

**Comment by ValentineHerr** [comment]
oh sorry I meant the species list in [this document](https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/doc/TreeDiseaseGuide/species_of_concern.md)

**Comment by teixeirak** [comment]
@irdangler generated that manually be reviewing this file: https://raw.githubusercontent.com/SCBI-ForestGEO/SCBImortality/main/R_results/mortrates_and_agbmort_by_species.csv, and the similar file for AU.rates. For each species in the tree_species_summary list, she checked which met the various criteria.

**Comment by ValentineHerr** [comment]
Oh I understand now. thanks for explaining.
I have almost the same list except I don't find qupr  and quve to be H but M, based on mort rates.

**Comment by ValentineHerr** [comment]
ha never mind, I forgot I was also looking at biomass mortality

**Comment by teixeirak** [comment]
If you're coding this, we can replace the manual entry with code. I'd like to update this in future years.

**Comment by ValentineHerr** [comment]
Yeah I am trying to code it. I am not quite there yet... caco does not get classified... I need to figure out why

**Comment by ValentineHerr** [comment]
ha, got it. And I have the same list.
Now to the "based on unhealthy one"
