### ISSUE TITLE
set up system for ground-truthing of lidar

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#66]
Eben Broadbent told me we could use lidar imagery of the forest to identify individual trees that can be used to align the remote sensing and on-the-ground data. I'd like to work that in with the field census protocol for this year.

**Comment by teixeirak** [comment]
@ebennb, how should this work, specifically? I'm envisioning that you might send images of trees you'd like ground-truthed, organized by expected location, and a field tech could then take those out on an ipad and retrieve tag numbers as they go?

**Comment by ebennb** [comment]
I think I can do this myself by matching the tree DBH with lidar trees and then interpolate all locations using each tree stems XY coordinates (once I get / download the data)? Then ask for confirmation from you and the tech may be looking at it to make sure it makes sense?

**Comment by teixeirak** [comment]
I'm not confident in the precision of our coordinates. Here's a link to a final presentation by an undergrad student who tried to reconcile drone imagery with the census data: https://www.dropbox.com/s/wdp09rw4a7kydvl/Final%20Presentation%20CONS%20496_Woolford%20%281%29.pptx?dl=0. Bottom line is that she was only able to confidently match 2 of 28 dominant/ co-dominant trees found dead with the drone imagery. Lidar has obvious advantages, but I still think the coordinates might be off enough that we'll need ground-truthing. 

Would it be possible for you to give this a try in the next month before we start the census (5/18)? If we're going to need to do some extensive ground truthing, I'd like to do it while this summer's intern, Erin, is with us.  

Of course, if you just need a handful of trees, it should be easy for someone to do the ground-truthing in one day.

**Comment by teixeirak** [comment]
This is a stale issue-- can reopen later if needed.
