### ISSUE TITLE
set up some basic analyses (parallel to Luke's)

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#67]
@ValentineHerr , @mageeluke , @djj4tree, 

The other day, Dan presented some plots by Luke of showing some basic analyses of the mortality censuses at SERC and Harvard Forest (FADs, etc.). I'm thinking it would be great to get those run for SCBI (would be helpful to @irdangler ), and perhaps even included in the CI (if easy).

@mageeluke , would you be willing to share your code?

**Comment by mageeluke** [comment]
Yes, we are assembling the code and can share soon.

**Comment by ValentineHerr** [comment]
Do we still want to do this?

**Comment by teixeirak** [comment]
This would be good to do, but is in no way urgent. I think I'll close this issue so that we keep issues to items that are important to address.
