### ISSUE TITLE
generate statistics/ plots on AU status

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#68]
@ValentineHerr , would it be easy to replicate the files [here](https://github.com/SCBI-ForestGEO/SCBImortality/tree/main/R_results) for the AU status? If so, could you please do so? 

This will be helpful for @irdangler (SMSC student).

**Comment by ValentineHerr** [comment]
Will try this now

**Comment by ValentineHerr** [comment]
@teixeirak, I added the tables and figures.

I understood to do the same calculations as for mortality (status A or AU becomes D) but looking at trees that were A and became AU at next census.

(also, I added a plot looking at mort rates and rates of A to AU for each size class, across years and species).

**Comment by teixeirak** [comment]
Thanks, this is great!

Although, could we also do this as just the fraction of living trees that are unhealthy (`AU/(A+AU)`)? 

The one you calculated is very valuable, but I think is rather hard to interpret given that definitions of AU were pretty subjective up until 2021.
