### ISSUE TITLE
make sure iPads are ready to go

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#70]

**Comment by jenajordan** [comment]
Okay. I will put aside time next week when I am at SCBI to do this (& read instructions ahead of time).

**Comment by teixeirak** [comment]
## Problems setting up the older iPad

@report from @jenajordan:

1- The older ipad was set up with @gonzalezeb's Apple ID. We need to switch this over to AppleID = ecoclimlab@gmail.com.  (Instructions [here](https://www.laptopmag.com/articles/how-to-change-apple-id-ipad).) @jenajordan , did it prompt for password. If so, we'll need that from @gonzalezeb (but securely, not via GitHub!).

2- Also, the older iPad doesn't seem compatible with latest dropbox. Dropbox is critical to our current setup, but I'd like to try to find a solution before giving up on the iPad.
