### ISSUE TITLE
set up CI system for 2022 census

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#73]

**Comment by teixeirak** [comment]
@ValentineHerr , 

could you please set up the CI system for the 2022 census (starting Wed), or be ready to switch it over once we have the first batch of data?

**Comment by ValentineHerr** [comment]
If all goes to plan, I should not need to do anything to set the new system up. As soon as the file in FFF_excel is overwritten by the first batch of data, the CI should get triggered. Fingers crossed! Please, do give me a heads up when the first batch is in so I can double check it is working.

I'll archive the "trace of reports" so we start fresh with those.

**Comment by teixeirak** [comment]
Awesome, thanks!

**Comment by teixeirak** [comment]
@emacmonigle , could you please try loading the data you've collected so far. There are instructions here: https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/doc/Protocols/FastField%20Download%20forms.md. Hopefully those work, but let us know if you run into any problems. I will send you the FFF password via email.

Then we'll check if the system setup is working as expected.

**Comment by teixeirak** [comment]
@ValentineHerr , Erin just tried pushing the first mortality census data, but the run is failing. The problem may be that there are now two files in the raw data folder.

**Comment by ValentineHerr** [comment]
@rudeboybert when you get a chance, can you check why script CI_4 is failing? It is working on my local machine but something is going wrong when it is run with GitHub Actions... Maybe it just needs more than one quadrat (unhappy to group_by only one group?)
Also, notice there were some column name issues in script CI_1 (see [this commit](https://github.com/SCBI-ForestGEO/SCBImortality/commit/769789f51675f1dbceb6e2e7a5fed9537464fd2b)), maybe that need to be fixed at Harvard too?

@teixeirak I updated the reports by hands for now.

**Comment by teixeirak** [comment]
Thanks, @ValentineHerr ! 

Why is the unhealthy_but_wrong_status being triggered for all these trees? (https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/testthat/reports/will_auto_fix/will_auto_fix_error_file.csv) I don't see what would do that...

**Comment by teixeirak** [comment]
Hmmm... and we're getting the same set of errors under required field fixes: https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/testthat/reports/requires_field_fix/require_field_fix_error_file.csv.

**Comment by ValentineHerr** [comment]
oh, I see.... it is because DWR is NA and the code is looking for "not False"... I wonder if it was entered differently last year.... I'll fix this now.

**Comment by ValentineHerr** [comment]
I think we have 2 tests that are technically testing the same thing:
- status_A_but_unhealthy (in require_field_fix_error_file)
- unhealthy_but_wrong_status (in will_auto_fix_error_file)  (this is supposed to be the "vice versa" of status_A_but_unhealthy  but I believe it is essentially detecting the same thing..., trees that have issues but that are not AU, DC or DS, so by default, that are A... )
Think I am going to remove the second test.

(It might be time to create csv similar to [this file](https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/testthat/README.md) but that would be directly readable/useable in R)....

**Comment by teixeirak** [comment]
> (It might be time to create csv similar to [this file](https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/testthat/README.md) but that would be directly readable/useable in R)....

Agreed! (Maybe @emacmonigle could take a crack at that on her next indoor day? Erin, I think this would be good for you in terms of knowing what tests are being run, and also a chance to engage with the computing side.)

**Comment by teixeirak** [comment]
@emacmonigle , please disregard the continuous integration results for now (but maybe fixed by the time you see this).

**Comment by teixeirak** [comment]
@emacmonigle , the CI is now working! (Thanks @ValentineHerr and @rudeboybert !) 

You can look at the [main page README](https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/README.md) to see status in terms of errors/ warnings (none from the first day!), progress, etc.

When there are errors that require a field fix, they will be recorded in a file in [this folder](https://github.com/SCBI-ForestGEO/SCBImortality/tree/main/testthat/reports/requires_field_fix). Great job on having none so far!

**Comment by ValentineHerr** [comment]
Fixed it and now it fails because there are a couple actual errors

**Comment by teixeirak** [comment]
Thanks, @ValentineHerr !

@emacmonigle , you now have a couple error reports that will show up when you sync Dropbox. (Note that currently I have to sync my GitHub to update the Dropbox folder (I have the GitHub repo downloading to my Dropbox so that when I pull from GitHub it updates a shared Dropbox folder. That's not ideal because it relies on me to pull in order for you to have all the files. You can either send me a message to pull the latest GitHub content or set it up in your own Dropbox (I'd have to explain how).
