### ISSUE TITLE
add "epicormics" as FAD?

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#74]
- [ ] in 2021 there are quite a few notes saying "epicormic branches", but nothing is entered in `epicormic.growth` as that column is reserved for fraxinus. Maybe it would be worth opening that column to all speices, like it is the case for `canaker...` or `wound` or `rotting trunk` ?

_Originally posted by @ValentineHerr in https://github.com/SCBI-ForestGEO/SCBImortality/issues/62#issuecomment-1013221217_

**Comment by djj4tree** [comment]
I would say epidemics are a symptom and not a potential.causal factor. I do
not think they qualify as a FAD.

**Comment by teixeirak** [comment]
Agreed. So we'll just continue putting them in notes. (Ideally, we'd have a field to note these, but probably not worth the effort required at this point.
