### ISSUE TITLE
Adding two FADs

### ISSUE THREAD

**Issue by mageeluke** [SCBI-ForestGEO/SCBImortality#78]
@teixeirak , we've encountered a few situations where a tree has epicormic sprouts, but with no FADs that fall under our current categories. We think adding a "epicormic sprouts" FAD option, might be good. 

Also, there are a few trees that have crown damage or a large percentage of the crown with no living branches (e.g. intact crown > 90, living crown < 60). The information is available from the data collected, but it might be nice to have a formal code for this, for example, "crown damage?"

**Comment by teixeirak** [comment]
This relates to issue #76, and so I'm flagging @emacmonigle here for her awareness of this discussion.

@djj4tree , what are your feelings on potentially adding/ redefining FADs? We obviously want to keep this standard across plots. Our recent assessment found that there's been a lot of inconsistency in how these codes have been applied, and so I think that it's important to have clear definitions ASAP (as Erin is already working on our census). I personally think that the past coding was enough of a mess that  I'd prioritize making sure the codes make sense going forward over maintaining consistency with past codes (although we should maintain compatibility).

**Comment by teixeirak** [comment]
> @teixeirak , we've encountered a few situations where a tree has epicormic sprouts, but with no FADs that fall under our current categories. We think adding a "epicormic sprouts" FAD option, might be good.

**I think it would make sense to note epicormic sprouts. That is, of course, a symptom of stress rather than a factor causing decline, but it seems worthwhile to note.**
> 
> Also, there are a few trees that have crown damage or a large percentage of the crown with no living branches (e.g. intact crown > 90, living crown < 60). The information is available from the data collected, but it might be nice to have a formal code for this, for example, "crown damage?"

**I'd only add something like this if it adds information to what we have with intact and living crown. For example, "recent breakage of major branch(es)" would give additional info.**

**Comment by emacmonigle** [comment]
On a similar note, I've come across some trees that have put out sprouts near the base of the trunk, which would be a sign of stress, but have no discernible FADs. The trees were also living, so I don't think it would fall under Dead with re-sprout. I've been making notes of sprouts at base of tree per @mageeluke 's last comment. Would these be grouped in epicormic sprouts, or should I continue clarifying base.

**Comment by emacmonigle** [comment]
On a similar note, I've come across some trees that have put out sprouts near the base of the trunk, which would be a sign of stress, but have no discernible FADs. The trees were also living, so I don't think it would fall under Dead with re-sprout. I've been making notes of sprouts at base of tree per @mageeluke 's last comment. Would these be grouped in epicormic sprouts, or should I continue clarifying base.

*Opps, I didn't mean to close that. Reopened

**Comment by teixeirak** [comment]
You can continue clarifying that these are at the base.
