### ISSUE TITLE
dispatch not working

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#79]
@jess-shue , 

@emacmonigle and I are trying to create a dispatch. It worked well until the point shown in the screenshot, but now seems to be frozen. Have you been able to create any dispatches?

<img width="1541" alt="image" src="https://user-images.githubusercontent.com/6355854/171650813-2f5fb1f3-199f-450b-bf83-e416087439ab.png">

**Comment by jess-shue** [comment]
@teixeirak @emacmonigle Yes, we are just working through that issue with Luke! 
Do you still have access to the 'Legacy Portal' on the left menu? I would try to click that and dispatch through there. If you don't see that button, you can dispatch by logging in to FFF's via this link:  https://portal.fastfieldforms.com/SubmissionActivity   

We are submitting help tickets - it is an issue with the New Portal!

**Comment by teixeirak** [comment]
Thanks, @mageeluke! I think we're all set on this for now.
