### ISSUE TITLE
assess and adjust data on trees with epicormics

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#8]
There are records of dead ash with non-zero epicormic scores for all years 2016-2020. CD (2020) counted trees as dead if they has nothing living but epicormics. I'm not sure if this was also true in previous years, or if people were counting dead epicormics. Checking with Erika.

**Comment by teixeirak** [comment]
I think the best way to address this will be to create a new status code, AE (alive only by epicormics).

**Comment by teixeirak** [comment]
Another option could be to just switch the code to the correct code, AU.

**Comment by teixeirak** [comment]
@jess-shue , @ValentineHerr , I'd like to call your attention to this issue. In past years, surveyors counted ash trees as dead if they were dead except for epicormics (e.g., category 5 in the EAB crown thinning assessment-- see [protocol](https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/Protocols/Mortality-Protocol-2021.pdf)). These should be alive unhealthy (or dead with resprouts if epicormics are around base), and should be coded AU, or we could create a new code, AE (alive only by epicormics). 

@ValentineHerr , we should retain the original spreadsheets and create new, corrected versions. I'd envision that this correction would be of perhaps many, where we apply various checks retrospectively and correct errors.

@jess-shue , it would be best to fix these in previous year status field that we use in the app, especially so that data required for new dead trees gets taken. I'm not sure if it would be possible to get that done today.

**Comment by jess-shue** [comment]
@teixeirak To clarify, you would like the previous status from 2020? I'm not sure if it would be best to add a new field or to edit that field. This may be something to discuss tomorrow in person to find the best solution.

**Comment by teixeirak** [comment]
Didn't the app you had set up for SERC note the status from the past year? To be clear, we definitely wouldn't want to have the field surveyors editing this field.

**Comment by jess-shue** [comment]
@teixeirak Yes, it has a field for 2020 status. Sorry, I was having trouble understanding what you wanted:  do you want to correct/update that status if the 2021 status denotes a resurrected tree?

**Comment by teixeirak** [comment]
The first step would be for @ValentineHerr to make a corrected version of the data file, and then you'd just use that to update what you're working with.

Until that's done, we'll want to treat every dead ash as if it's newly dead and record the required info.

**Comment by ValentineHerr** [comment]
@teixeirak,
To be sure I understand what you are saying: 

1- I look at ash trees with a "D" in their status (all codes with a D are either dead trees or trees not found/only tag found).
2- of those, if `fraxinus.crown.thinning = 5` and  `fraxinus.epicormic.growth>0` I should change status to `AU` ?
3- I should do this for all previous censuses (2020 as priority to give to @jess-shue)
4- I save the new files (where?). Should I just update the files in the `data` folder or do you think it is better to replace the raw data?

**Comment by teixeirak** [comment]
> 1- I look at ash trees with a "D" in their status (all codes with a D are either dead trees or trees not found/only tag found).

I think all cases will be DS, but it wouldn't hurt to check for DC (no DC cases in 2020 census). Keep in mind that this is just for ash (or CHVI).

**Comment by teixeirak** [comment]
> 2- of those, if `fraxinus.crown.thinning = 5` and `fraxinus.epicormic.growth>0` I should change status to `AU` ?

Almost. DS should change to  AU if `fraxinus.crown.thinning ≤ 5` and `fraxinus.epicormic.growth>0`.

**Comment by teixeirak** [comment]
> 3- I should do this for all previous censuses (2020 as priority to give to @jess-shue)

Correct.

**Comment by teixeirak** [comment]
> 4- I save the new files (where?). Should I just update the files in the `data` folder or do you think it is better to replace the raw data?

We don't want to change the raw data files, so I think we just change the files in `data`. Honestly, I'm not quite clear on the difference between files in `raw_data` and `data`.

**Comment by ValentineHerr** [comment]
> > 4- I save the new files (where?). Should I just update the files in the `data` folder or do you think it is better to replace the raw data?
> 
> We don't want to change the raw data files, so I think we just change the files in `data`. Honestly, I'm not quite clear on the difference between files in `raw_data` and `data`.

Files in `data` are generated by [this script](https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/R_scripts/1-Creating_data_files_from_raw_data.R), which fixes a lot of issues. So yeah, it makes sense to add this fix to that script and save the files in `data`. I thought you had something else in mind when you were saying to create an new original spreadsheets.


Will work on this now.

**Comment by teixeirak** [comment]
okay, thanks!

**Comment by ValentineHerr** [comment]
> > 1- I look at ash trees with a "D" in their status (all codes with a D are either dead trees or trees not found/only tag found).
> 
> I think all cases will be DS, but it wouldn't hurt to check for DC (no DC cases in 2020 census). Keep in mind that this is just for ash (or CHVI).

(I see 3 cases with status DC in 2020 census : tags 150975, 163373, 161502)

**Comment by teixeirak** [comment]
Right, I see those too. They all have `fraxinus.epicormic.growth`=0, though, so they are legitimately dead.

**Comment by ValentineHerr** [comment]
(sorry, these cases do not fill other criteria)

**Comment by ValentineHerr** [comment]
Ok, I updated the files in the `data` folder.
@jess-shue, you can use [this file](https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/data/mortality_2020.csv) to generate the pre-known info in the forms. Let me know if it is missing some columns as I think I pointed you to the raw data previously.

**Comment by teixeirak** [comment]
@jess-shue , please let us know when this is fixed, and then you (or someone) can close this issue.

**Comment by jess-shue** [comment]
@teixeirak  and @ValentineHerr 
The app is now updated with the data from Valentine. The file only included gx and gy which is hard to interpret on the 20x20 grid in the field. I was able to merge lx and ly from the 2013 data temporarily (could be old and lack corrections from latest census), but @ValentineHerr would it be possible to add the lx and ly columns to this mortality_2020.csv?

**Comment by ValentineHerr** [comment]
@jess-shue the current [mortality_2020.csv](https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/data/mortality_2020.csv) file should now have local coordinates.

**Comment by jess-shue** [comment]
@ValentineHerr Thank you! There are a fair number of NA's in the lx, ly column; any solutions for those?

**Comment by ValentineHerr** [comment]
oops... sorry, I assumed the data was complete and didn't check. let me redo this differently.

**Comment by ValentineHerr** [comment]
@jess-shue I updated mortality_2020.csv file. all tags should have local coordinates now... I ended up recalculating them but some are negative... which would mean that the quadrat or gx or gy are wrong...

What file were you looking at when you merged the local coordinates from 2013 data?

**Comment by jess-shue** [comment]
@ValentineHerr Thank you! I'll try and update the app again later today. I'll be in the field the next few days assisting a graduate student. I had a 2013 census file from assisting with building an app for the 2018 census, so it was not likely the best to use.

**Comment by ValentineHerr** [comment]
I think we can close this
