### ISSUE TITLE
CI failing

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#80]
@ValentineHerr , FYI, something is going wrong with the CI (failing to run).

**Comment by ValentineHerr** [comment]
CI is fixed, the problem was the length of the newest FFF file name. @emacmonigle, when you push a new file, make sure the name is not too long, it just need to be the only file with "2022" in its name for the CI to work.

**Comment by teixeirak** [comment]
It seems to have failed again.

**Comment by teixeirak** [comment]
Okay, this is working now. Thanks, @ValentineHerr !

@emacmonigle , you can now see the full up-to-date report. Please dispatch and fix the errors as soon as you get a chance to avoid a backlog, and to get the learning benefit (but let us know if any errors seem inappropriate).
