### ISSUE TITLE
Require crown position for dead standing trees

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#81]
@jess-shue , when a tree is DS, the current FFF removes the requirement to record crown position. This should be required.

**Comment by teixeirak** [comment]
Oh, that's right! Okay, we should leave as is then. 

I'll leave this open to clarify in the field guide.

**Comment by jess-shue** [comment]
OK, will not change this rule then!

**Comment by jess-shue** [comment]
Crown position and dead crown position now required for DS trees in the app.
