### ISSUE TITLE
remove "High" "Moderate" and "Low" fields from FFF output file

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#84]
@jess-shue , not an urgent fix, but next time you update FFF, could you please remove the "High" "Moderate" and "Low" fields from the output? (if possible)

**Comment by jess-shue** [comment]
Yes, I can 'exclude them from report' and they should then be out of the way. Good idea!

**Comment by jess-shue** [comment]
@teixeirak This should now be fixed, but let's leave this open until @emacmonigle collects and submits more data next week just to be sure.

**Comment by teixeirak** [comment]
@emacmonigle , please verify that this is working as expected and then close this issue.

**Comment by emacmonigle** [comment]
@teixeirak I'm not quite sure which "High", "Moderate", and "Low" is mentioned here. Are we removing the "Moderate" and "High" warning in FF to remind surveyor to take extra care in health review?

**Comment by teixeirak** [comment]
We're keeping the warnings. It's just that the text for each warning level was printing out in the output data sheets, which was unnecessary and annoying.
