### ISSUE TITLE
DWR for AU

### ISSUE THREAD

**Issue by emacmonigle** [SCBI-ForestGEO/SCBImortality#86]
@jess-shue The FF gives an option for dead with resprout when tree is AU. If DWR is selected when the tree is AU, it produces an error. Would it be possible to remove the DWR option from A and AU trees to ensure this error doesn't happen accidentally?

**Comment by jess-shue** [comment]
@emacmonigle DWR should no longer show if A or AU is selected - now on Version 16. I have to be careful when setting these rules, as sometimes they cancel one another out in some way and errors in functionality occur. Hopefully, we're close to having things set for you!

**Comment by emacmonigle** [comment]
@jess-shue thank you for that update! Should be helpful since the A/AU with DWR error is not stated in the protocol, so this can help future surveyors not create these errors. 

If there's any request to the FFF that I make that is causing too many errors or would cancel something out, then no worries. Please let me know so I can make a note on the protocol so that the instructions for future surveys will prevent errors from the start.
