### ISSUE TITLE
CI Failing with new file upload and name

### ISSUE THREAD

**Issue by emacmonigle** [SCBI-ForestGEO/SCBImortality#88]
@ValentineHerr @teixeirak Just pushed the newest file with all the FF data using instructions from issue #87. The name was shorter this time: "SCBI Mortality 2022," but still got "data-test: All jobs have failed" error. If there's anything I can try please let me know, or I can detail the steps I took to see if its a user error. 

Also haven't done step 8 and 9 of issue #87 since I don't know which quads gave errors yet since the CI failed.

**Comment by teixeirak** [comment]
I think this is resolved.
