### ISSUE TITLE
get on track to finish census on time / drop Fraxinus <10cm?

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#90]
At our current pace, it's looking like a challenge to get this census done on time. We're currently at 20% complete with less than half of the expected person-days complete.  There are a number of reasons why we may be able to move faster in the 2nd half of the summer, but I'm still concerned that we won't make it. 

One way to speed things up would be to drop the census of Fraxinus <10 cm. @jenajordan , can you please give me your perspective as to how much you think this would speed things up? @ValentineHerr , could you please give a quick calculation of how that would affect the number of stems left (also n censused so far)?

**Comment by jenajordan** [comment]
@teixeirak Removing all Fraxinus < 10 cm removes 800 stems I believe. Removing Fraxinus that were previously dead (all DBH) removes 748 stems I believe (but some have already been done).  Question - are we keeping trees that were previously dead in prior 2 censuses? If yes, why? Those might be ones to remove too? Spending time looking for dead trees eats up time (that said, on rare occasion one that was 'dead' last census I find living this one).  BTW - the % complete is not updated. For example, I have completed ~28 quads in the deer exclosure but only 12 are showing on the completion map. Erin said she was having difficulty with CI/ having completed quads show on the map. I think we will speed up a bit

**Comment by ValentineHerr** [comment]
I'll check CI.

**Comment by ValentineHerr** [comment]
@jenajordanm  Are you sure you pushed the latest data? the last push is Jun 22.

**Comment by teixeirak** [comment]
> Question - are we keeping trees that were previously dead in prior 2 censuses? If yes, why? Those might be ones to remove too?

What's our current protocol? I agree that there's little point in returning to dead down trees, and no point in doing so after they've been found dead twice. We do want to continue to monitor standing dead trees until they fall, as they show up in aerial sensing (and because that info on how long they stay up is valuable).

**Comment by ValentineHerr** [comment]
The last push is from Erin on 6/22. so it is up to that date.

**Comment by teixeirak** [comment]
@jenajordan , the instructions for downloading from FastField & uploading to GitHub are here: https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/doc/Protocols/FastField%20Download.md. Unfortunately it's a bit of a clunky system (moreso than the dendro bands).

**Comment by ValentineHerr** [comment]
@jenajordan let me know if you run into issues and we can get on a call.

**Comment by jenajordan** [comment]
@ValentineHerr thanks - I will download tomorrow eve when I back with the iPad. I'll let you know if I run into issues.

**Comment by jenajordan** [comment]
@ValentineHerr and @teixeirak - I just followed the instructions to download from FastField/ upload to Github. It looks like the map is updated re the quadrats I've completed. 22% done to date.

**Comment by jenajordan** [comment]
> I believe there were 13,451 stems in the 2021 mortality census.

**Comment by teixeirak** [comment]
Thanks, @jenajordan. 

So, to summarize where this stands: 
- we could drop ~800 live ash ≤10 cm, or ~6% of stems (but often harder to find). This is not ideal, but better than not finishing the census.
- we could drop recensus of any dead ash ≤10cm. I'm not sure how many fit into this category, but they tend to be hard to find.
- are we currently returning to any dead down stems? If so, we can drop that.

**Comment by teixeirak** [comment]
I'd like to make 2 changes:
1) drop all ash <10cm
2) ensure that we're not revisiting any stems that were both: (a) dead 2 years in a row AND (b) down or missing in the last census. That is, if a stem was live in 2020 and dead or missing in 2021, we revisit it this year to confirm death. We need to continue revisiting dead standing until they fall, but once they fall or go missing, we can drop them.

@jess-shue , could you please modify the FastField form accordingly?

@ValentineHerr , this may affect some of the error checks going forward, and we can also drop any existing errors where these stems were missed or have incomplete info.

**Comment by jess-shue** [comment]
@teixeirak I can remove ash < 10 cm. The second filtering of stems is more difficult, but I will give it a try!

I will keep the current form intact and create a new form - in case we need to go back to how things started this summer.

**Comment by teixeirak** [comment]
Thanks, @jess-shue !

**Comment by emacmonigle** [comment]
@jenajordan @ValentineHerr Jen were you able to push the downloads from FF to the CI without errors? If so, could either of you get on a call possibly tomorrow and walk me through how because I'm still running into errors when I push files onto github and I'm not sure why.

**Comment by jenajordan** [comment]
I keep pushing but it doesn't reflect in the map. I'm confused ss well. I am following the directions for submissions in fastfield etc

**Comment by ValentineHerr** [comment]
It looks like there is something wrong when the script "Generate reports" is running. I'll check in about 1h, after a meeting.

**Comment by ValentineHerr** [comment]
The problem is because the excel file format changed.
The script is looking for a sheet called "subform_1", which does not exist anymore.

Did one of you change the way you downloaded the excel file from FFF or is it the new output of FFF?

**Comment by jess-shue** [comment]
The form they are currently using was last updated on June 17th. The FastField Forms website has undergone some updates over the last year, so this may be a change in the system. I attempted to download files from last year as well as this year, and both have the following sheets in the excel files:
section_1
section_2
multiphoto_picker_1
Form Meta Data
Root

**Comment by djj4tree** [comment]
This is strange because our forms for other sites are still coming with the 'subform_1' tab.

**Comment by jess-shue** [comment]
@djj4tree I'm not sure either, but because their form has a second section for ash details it may be exporting differently with the newer FFF's platform. 
I've attempted to download the data using the old platform, and that seems to export with a 'subform_1' sheet - it is empty though. @ValentineHerr, is the subform_1 sheet empty, but there are still 'section_1' and 'section_2' sheets?

If we just need the blank sheet named 'subform_1' we can either download the data via the old portal using this [link](https://portal.fastfieldforms.com/SubmissionActivity) or, simply have them add a blank 'subform_1' sheet after downloading from the current portal.

**Comment by ValentineHerr** [comment]
The 'subform_1' is where all the data was and that is what the script is loading.

I can change the SCBI script to read 'section_1' + 'section_2' instead of 'subform_1'.
@jess-shue, are you able to tell if 'subform_1' is just the concatenation of  'section_1' and 'section_2' or is it more complication than that (e.g. need merging on some key column ?)

**Comment by ValentineHerr** [comment]
Never mind, @jess-shue, I think I can see that section 1 and section 2 can be directly "concatenated" (but I may merge them by Tag and/or submission ID, to be sure)

**Comment by jess-shue** [comment]
@ValentineHerrGreat! I was just typing a response:

'section_1' contains the main dataset, 'section_2' contains the extra ash fields and a row for each stem with those columns. 'Tag' and 'StemTag' are in both sheets, and a merge should work based on those columns.

**Comment by ValentineHerr** [comment]
@jenajordan and @emacmonigle, this is fixed now. The files should be updated (although the dashboard sometimes takes a while to update).

% complete is now 25%.

**Comment by teixeirak** [comment]
I'm going to close this issue and open a couple others related to speeding up the census.

**Comment by djj4tree** [comment]
Dead and downed trees could be removed with no consequence to the
mortality study (unless you code down and dead trees for something), but
dead standing trees need to be revisited to obtain crown information.
