### ISSUE TITLE
drop EAB add-on (at least temporarily)

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#92]
From a conversation with @emacmonigle , I decided it would be best to completely drop the EAB add-on, at least temporarily.  That is, stop collecting EAB-specific info for ash >10cm. We've already dropped ash <10cm.

I don't think there's any need to remove from the form, and its probably better to keep it there in case we have time to go back and get it. But let me know if you see it differently, @emacmonigle / @jess-shue .

@ValentineHerr / @emacmonigle , can you please downgrade missing EAB info from an error to a warning? (@emacmonigle , I know you were helping with the error/warning system earlier, but don't know if you got to the point of being able to do that.) If we decide we have time to get it later, we can switch it back.

**Comment by jess-shue** [comment]
@teixeirak Yes, it sounds like we shouldn't touch the form as I've already caused problems by creating a second form to eliminate the small stems. Sorry about this, but certainly best to leave the form as-is and just skip entering any data.

**Comment by ValentineHerr** [comment]
agreed

**Comment by ValentineHerr** [comment]
I downgraded missing EAB info from an error to a warning but CI won't work until the `Crown position < 10 cm DBH` is back in the file. @emacmonigle or @jenajordan, when you get a chance, please re-download the data, make sure that column is back, and then push here.

**Comment by ValentineHerr** [comment]
never mind @emacmonigle or @jenajordan, I had not seen [this comment ](https://github.com/SCBI-ForestGEO/SCBImortality/issues/91#issuecomment-1199863264)
