### ISSUE TITLE
Mistyped Quad Title in FFF

### ISSUE THREAD

**Issue by emacmonigle** [SCBI-ForestGEO/SCBImortality#95]
@jess-shue Yesterday I noticed I submitted the wrong number at the quad level, but still completed the stems in the right FF data sheet. I submitted 1606 as 1608, but then continued to do 1608 as well. This means there is two 1608 quads, but one of them should be 1606 

In the excel, there is two 1608 quads and I know what I need to fix but I'm not exactly sure how. Should I go through R and make it a autofix, or can I fix it from the FF side so the original data is correct. Can you help show me how to fix this error?

**Comment by djj4tree** [comment]
We would normally dispatch the incorrect FFF and fix it there.
Dan

**Comment by jess-shue** [comment]
@emacmonigle Dan's suggestion does work well and is probably the easiest/quickest if you're able to dispatch files easily. You can also edit the data in FFF's to make a quick fix, but it isn't letting me do so right now - taking forever to load.

1. Go to submissions - you can use the filters to find the files you need. I selected 'Yesterday', 'SCBI Mortality 2022', and 'Display Mask' equal to 1608
2. After filtering, you should hopefully have a short list of files to check. You can click the 'Action' button and 'View Form' to check them and confirm which file needs to be edited. At this point, you can dispatch the form and edit, resubmit, as Dan suggested.
3. Or, if it would load, you could select 'Action' -> 'Edit Submission' and change the Quadrat on the landing page of the app. But, with our data being as bulky as it is I think FFF's webpage is having trouble loading it.

So, Dan's suggestion is best! Are you able to dispatch that form?

**Comment by jess-shue** [comment]
@emacmonigle The editor did finally load, and I can change the quadrat name - but I don't want to do that if you've dispatched! I'll leave it with you, but let me know.

**Comment by emacmonigle** [comment]
@jess-shue Just dispatched, I can take care of it. Thanks for your help!

**Comment by teixeirak** [comment]
I think we can close this.
