### ISSUE TITLE
Notes of fixes for 2022

### ISSUE THREAD

**Issue by mageeluke** [SCBI-ForestGEO/SCBImortality#96]
@teixeirak @ValentineHerr, here are a couple notes from the field this year.

- [x] One large FRAAME, tag 133461 is a hickory-- I think CARCOR, although I'm not totally certain. Alive and healthy. 

- [x] 152645, large QUEVEL coded as  "DN" for 2022, this tree is "DC" --uprooted 

- [x] Another large QUEVEL, Tag152618, looked dead to me (98% certain)
     crown intact = 86%, living = 0%
     Crown position = 4
     Liana = 25% 
     FADs: Fungus, Unable to determine, Complete defoliation

Lastly, tag 10642 is worth looking at further. This tree appeared alive and healthy to me, and for an ash tree of this size, this was awesome to see. This might be an example of a 'lingering ash.' I looked at all other ash > 25 cm that were alive from last year, all were dead or nearly so.

**Comment by teixeirak** [comment]
Thanks @mageeluke !

@ValentineHerr , when you have a chance, could you please code in these fixes?

**Comment by ValentineHerr** [comment]
> One large FRAAME, tag 133461 is a hickory-- I think CARCOR, although I'm not totally certain. Alive and healthy.


Looks like that tag has been tricky because it looks like a 2-stemed FRAAME but is in fact 2 trees, one FRAAME and one CARCOR...

Here is what I have in my notes:

> - "tag 133461 StemTag 1 (bigger stem) (quadrat 1316, comment in 2015: Ojo:this is not caco, it is fram. Not 2 stem! Fram tag=131352)"
>    - looks like the bigger stem has a different tag and is fram. After 2018 main census, the tag and species were fixed but the species of the smaller stem (tag 133461), which was originally caco, was also changed to fram, not sure if it was made on purpose. I will do the same here...

So I'll check and make sure that 133461 remains has hickory

**Comment by ValentineHerr** [comment]
> > One large FRAAME, tag 133461 is a hickory-- I think CARCOR, although I'm not totally certain. Alive and healthy.
> 
> Looks like that tag has been tricky because it looks like a 2-stemed FRAAME but is in fact 2 trees, one FRAAME and one CARCOR...
> 
> Here is what I have in my notes:
> 
> > * "tag 133461 StemTag 1 (bigger stem) (quadrat 1316, comment in 2015: Ojo:this is not caco, it is fram. Not 2 stem! Fram tag=131352)"
> >   
> >   * looks like the bigger stem has a different tag and is fram. After 2018 main census, the tag and species were fixed but the species of the smaller stem (tag 133461), which was originally caco, was also changed to fram, not sure if it was made on purpose. I will do the same here...
> 
> So I'll check and make sure that 133461 remains has hickory

This is too confusing and will ask the crew to be careful and figure out what these two stems, tags and species are.

**Comment by teixeirak** [comment]
@jess-shue said she'll check this today or tomorrow. Flagging her here so she's connected to the thread.

**Comment by jess-shue** [comment]
OK, sorry, I swear I had checked these stems before and maybe never sent what I had found! 
133461 - is the smaller tree and is a caco
131352 - was a large fram this is down and dead

**Comment by ValentineHerr** [comment]
Thank you so much @jess-shue, we can close this now
