### ISSUE TITLE
assess 2022 census errors

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#97]
@ValentineHerr , the census is now "complete", with all data loaded, and the next step is to assess the errors.

We have a long list of errors, but I believe that many of them are false errors-- for example, "missing stem" on stems that we dropped from the census.  For instance, all Fraxinus <10cm should be dropped from the set of expected stems. We'll probably need to have some team discussion or reference issues (e.g., #90, #92) to recall what we changed mid-census.

It would be helpful to create a histogram of error types, which we can use to review/ reclassify errors and to plan next steps.

**Comment by ValentineHerr** [comment]
working on this now

**Comment by ValentineHerr** [comment]
![image](https://user-images.githubusercontent.com/19673377/197858459-a4ef8038-e35c-4248-b9d2-3708b881599c.png)

![image](https://user-images.githubusercontent.com/19673377/197858498-b8ad53a0-248c-4a34-8d7c-35de20cd7714.png)

![image](https://user-images.githubusercontent.com/19673377/197858543-f3385172-27bd-45db-ba7a-e7cab4a25d7d.png)

**Comment by ValentineHerr** [comment]
![image](https://user-images.githubusercontent.com/19673377/197859833-0c151d54-a443-494b-bbb8-2b146e5d7ad4.png)

**Comment by teixeirak** [comment]
Thanks for working on this, @ValentineHerr! 

It's reassuring to see that most of our errors are Fraxinus, which we dropped from the census. 

We'll want to modify the table of tests, found [here](https://github.com/SCBI-ForestGEO/SCBImortality/tree/main/testthat). I note that the most recent file there was created by @emacmonigle . Which file is the script using?

**Comment by ValentineHerr** [comment]
@teixeirak,
Are the plots above enough to identify what errors might be real ones?

I am considering revamping "Generate report" by making a function that would allow to turn on/off some error detections as needed (using date thresholds).  That would be quite a bit of work so let me know if you think it is worth it, if you feel that the scenario that happened this year is likely to happen again.

**Comment by ValentineHerr** [comment]
> Thanks for working on this, @ValentineHerr!
> 
> It's reassuring to see that most of our errors are Fraxinus, which we dropped from the census.
> 
> We'll want to modify the table of tests, found [here](https://github.com/SCBI-ForestGEO/SCBImortality/tree/main/testthat). I note that the most recent file there was created by @emacmonigle . Which file is the script using?


The script is not using any file. It takes someone to rewrite the script.
I have been wanting to create a file, similar to that table, but that the script would be able to read directly. And, because I dont' think it is a good idea to just drop some tests in the middle of the census, I am trying to think if there would be a way to turn on/off some test at certain dates.... I feel that it would be useful, but I anticipate it will be quite a bit of work.

**Comment by ValentineHerr** [comment]
Another reason would be that the main census could use the same table of tests, except the tests relevant to the mortality census would be turned off.

**Comment by teixeirak** [comment]
I think the plots are good. I don't think we need to -- or should-- classify errors differently by date. So, for instance, the fact that we dropped small Fraxinus stems and EAB-specific records will mean that missing stems <10cm are never counted as an error, missing EAB info is never counted as an error, etc. I think I want to change those all to warnings (to preserve the record that we originally wanted to get them).

There will be a few other changes to criteria as well.

**Comment by ValentineHerr** [comment]
ok sounds good.

I do think we need a better system with a table that we can edit and that automatically gets read by the script to determine the type of errors or warnings to detect.
As it is, the script has been edited too many times in a somewhat rushed way and we have no way of knowing if the latest changes in the table of tests have been implemented in the script.

**Comment by teixeirak** [comment]
How much work would it be to switch to a table? This is probably our last year using FastField for the data collection step, so maybe not worth it? What do you think makes the most sense?

**Comment by ValentineHerr** [comment]
Oh that is right....

Do you think we will try to implement the mortality error tests in the GIS app? If yes, then, indeed, no need to work on this.

**Comment by ValentineHerr** [comment]
This is the new field fix error breakdown:

![image](https://user-images.githubusercontent.com/19673377/198319835-e97a50f2-c6bf-4ebd-8745-21ad93fe5d3c.png)

**Comment by djj4tree** [comment]
If there are photos then a lot of those wounds, rot and canker with no
levels can be fixed in the office.

**Comment by teixeirak** [comment]
@ValentineHerr , here's a running list of fixes/modifications to the tests:

- [ ] exit_hole_count_.... - change from error to warning
- [ ] missing_percent_crown_living for DS trees: change to auto-fix error, fill with "0".

**Comment by teixeirak** [comment]
> If there are photos then a lot of those wounds, rot and canker with no levels can be fixed in the office.

@djj4tree , What's the most efficient way to access the photos?

**Comment by djj4tree** [comment]
@mageeluke has done this. He might be able to comment on effienct ways

**Comment by ValentineHerr** [comment]
> * update criteria for inclusion: ensure that we're not expecting data from any stems that were both: (a) dead 2 years in a row AND (b) down or missing in the last census. That is, if a stem was live in 2020 and dead or missing in 2021, we revisit it this year to confirm death. We need to continue revisiting dead standing until they fall, but once they fall or go missing, we can drop them.

@teixeirak do we consider "PD" as missing? If not, this statement ends up flagging more missed trees than before.
For example, status history `A;A;A;A;A;A;A;DS;PD;PD` will be expected to be censused because `a = TRUE` but `b = FALSE` so `a AND b = FALSE`

**Comment by ValentineHerr** [comment]
> * [ ]  create new category for errors: photo_fix. Include the following: canker_but_no_level, rot_but_no_level, wounded_but_no_level.
> *

I won't have time to code this today, (this has complicated consequences, for generating the map, the reports etc...)

**Comment by mageeluke** [comment]
@ValentineHerr, @teixeirak, @djj4tree, sorry for my delayed response. If submissions are downloaded as a pdf, the images should be embedded in the document. It might have to be two separate files due to limits on pdf sizes. 


![Fastfields submissions](https://user-images.githubusercontent.com/47282393/202055598-19db8eff-5d51-4cc9-a07f-8585b4882102.JPG)

**Comment by teixeirak** [comment]
> > * [ ]   create new category for errors: photo_fix. Include the following: canker_but_no_level, rot_but_no_level, wounded_but_no_level.
> 
> I won't have time to code this today, (this has complicated consequences, for generating the map, the reports etc...)

@ValentineHerr , where does this stand (photo fix errors)? Where do those errors show up currently ? (I'm asking because we're hopefully close to being ready to get back out in the field and get the field fixes. )

**Comment by ValentineHerr** [comment]
Is this really worth coding? Can you filter the report for the errors you are looking for?

**Comment by teixeirak** [comment]
Yeah, perhaps not worth coding, although these currently show up in field_fix_errors and could send people back to the trees unnecessarily. It would work if these get resolved first (#100 ) or if people just know they can be skipped in the field.

**Comment by ValentineHerr** [comment]
I can change them to auto_fix

**Comment by teixeirak** [comment]
I think that would be better. Perhaps rename lab_fix.

**Comment by ValentineHerr** [comment]
I changed those 3 errors to the auto_fix file. There are a lot of dependencies on name in the CI system, so I opted not to rename the file.

**Comment by ValentineHerr** [comment]
I think we can close this
