### ISSUE TITLE
Code the auto fixes

### ISSUE THREAD

**Issue by ValentineHerr** [SCBI-ForestGEO/SCBImortality#98]
WILL AUTO FIX RULES:
- [x] `canker_bu_no_level` (n= 19)  **--> ignore (leave canker level as NA) - VALIDATED BY @teixeirak**
- [x] `canker_level_but_wrong_status_or_FAD` (n = 2) **--> add K in FAD, ensure status is AU - VALIDATED BY @teixeirak**
- [x] `DBH_dead_suspicious` (n = 3) **-->  when previous status was dead (DS, DC, PD), replace measurements with `NA`**
- [x] `missing_crown_position_while_dead_crown_position_is_recorded` (n = 14) #106, see  also #102 
- [x] `rot_but_no_level` (n=34) **--> ignore (leave rot level as NA) - VALIDATED BY @teixeirak**
- [x] `wounded_but_no_level` (n=64) **--> ignore (leave wound level as NA) - VALIDATED BY @teixeirak**
- [x] `wounded_level_but_wrong_status_or_FAD` (n = 64) ) **--> add W in FAD,  ensure status is AU - VALIDATED BY @teixeirak**

I had written this but we don't need it:
- [x] `missing_percent_crown_living` (n = 0) **-->for DS trees: fill with "0".**

WARNING - do we want to auto-fix anything?
- [x] `crown_thinning_more_than_1_but_not_AU_or_dead` (n = 10) - **change to AU**
- [x] `Dead_but_now_alive` (n=33) **--> change previous status to alive, see #105**
- [x] `EABF_recorded_but_not_AU_or_dead` (n = 14) **--> change to AU**
- [x] `epicormic_growth_but_not_AU` (n = 11) **--> change to AU - VALIDATED BY @teixeirak**
- [x] `exit_hole_count_no_DE_EABF` (n = 2) **--> add DE - VALIDATEDBY @teixeirak**
- [x] `missing_EAB_info` (n = 142) **--> ignore**
- [x] `missing_stem` (n = 552) **-->ignore - VALIDATED BY @teixeirak**
- [x] `status_DS_or_DC_but_DBH_not_measured` (n = 30) **--> ignore (dead DBH = NA)**

**Comment by ValentineHerr** [comment]
@teixeirak, can you help filling out the rules for the auto-fixes?

What do we want to do with the wranings?  I am working on a file for status history of 'Dead_but_now_alive'

**Comment by teixeirak** [comment]
﻿Thanks, Valentine!

Status 'Dead_but_now_alive' does not call into question any of this years’ data, but does imply that data from past censuses was incorrect. I’m not sure if the protocol should be to retroactively correct those records or let stand. I’ll inquire.

**Comment by ValentineHerr** [comment]
@teixeirak, we need to decide what to do with all the element of the list in the first comment of this issue before I clean up 2022 data.

**Comment by teixeirak** [comment]
> * `DC_but_now_A_AU_or_DS` (n = 1)

was this previously DS or alive?

**Comment by ValentineHerr** [comment]
It was `DC` in 2021 and is now `A`... So, in this case it is the same as `Dead_but_now_alive`. 
I am not sure why we have this `DC_but_now_A_AU_or_DS` test.... Maybe I should change it to be `DC_but_now_DS` (as a tree dead down can't become dead standing). What do you think?

**Comment by teixeirak** [comment]
> Maybe I should change it to be `DC_but_now_DS` (as a tree dead down can't become dead standing). What do you think?

Yes, that's a more informative test.

**Comment by ValentineHerr** [comment]
@teixeirak, I am saying:

`exit_hole_count_no_DE_EABF ` -->  "add DE"

and `epicormic_growth_but_not_AU` --> change to AU

let me know if now OK

**Comment by teixeirak** [comment]
> and `epicormic_growth_but_not_AU` --> change to AU

I'm not sure I'm confortable with this. How many of these are ash?

**Comment by ValentineHerr** [comment]
> > and `epicormic_growth_but_not_AU` --> change to AU
> 
> I'm not sure I'm confortable with this. How many of these are ash?

chvi n = 1
fram n = 6
frni n = 1
frpe n = 3

**Comment by ValentineHerr** [comment]
I added some rules to be verified (remove **TO VALIDATE BY @teixeirak** if you agree)

**Comment by teixeirak** [comment]
> > > and `epicormic_growth_but_not_AU` --> change to AU
> > 
> > 
> > I'm not sure I'm confortable with this. How many of these are ash?
> 
> chvi n = 1 fram n = 6 frni n = 1 frpe n = 3

Okay, go ahead and stick with that rule.

**Comment by teixeirak** [comment]
> * `missing_crown_position_while_dead_crown_position_is_recorded` (n = 14)

This is linked to issue #102

**Comment by ValentineHerr** [comment]
@teixeirak, I am now noticing that for those issues like "Canker_but_no_level" or "Rot_but_no_level"..., there is often (but not always) a value for another level (e.g. a value in wound level when FAD is R, or vice-versa...)

here is an example:
![image](https://user-images.githubusercontent.com/19673377/224722109-d3aeaf05-c5f8-471f-a876-f0cdb06e7d83.png)


I don't know if there was a mismatch of a Wound vs a Rot or a Canker... but I guess we would not know if it is the level or the letter that is correct...

**Comment by teixeirak** [comment]
Most of those examples were recorded by @jenajordan . I'm flagging her to see if she remembers what might be going on.

**Comment by jenajordan** [comment]
@teixeirak and @ValentineHerr , I just looked into it. What I think happened is I didn't realize I should note rot in 2 places (when noting FAD of R, it then states to note wound size on main stem (which is the rot in these cases). So under Rotting it would be the same number (here mostly 1s, a few 2s). Is that what is being asked?

**Comment by teixeirak** [comment]
This sounds like another place where the instructions weren't clear-- will need to fix for the census this year. Wound and rot are actually defined differently.

To fix here, @ValentineHerr , for instances like this, please transfer the wound level to rot level.
