### ISSUE TITLE
system for easier error fixing

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#99]
@ValentineHerr , it's quite clunky to re-deploy all quadrats with errors on FastField Forms. I think it would be faster if we had a file where we could just record the fixes. Do you think we could easily arrange something like this?

**Comment by ValentineHerr** [comment]
Sorry I had to leave early yesterday.

Yeah, we can edit the record manually if it is easier... you can print a page of trees to revisit.
________________________________
From: Kristina Anderson-Teixeira ***@***.***>
Sent: Tuesday, November 8, 2022 4:17:14 PM
To: SCBI-ForestGEO/SCBImortality ***@***.***>
Cc: Herrmann, Valentine ***@***.***>; Mention ***@***.***>
Subject: [SCBI-ForestGEO/SCBImortality] system for easier error fixing (Issue #99)


External Email - Exercise Caution

@ValentineHerr<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FValentineHerr&data=05%7C01%7Cherrmannv%40si.edu%7C0555107e662b48ad643b08dac1ce9ba2%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C638035390358014229%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WfCmIQaw3IpEnydoQTJt8WMO9GoMlrBjIw0LTuEVMz4%3D&reserved=0> , it's quite clunky to re-deploy all quadrats with errors on FastField Forms. I think it would be faster if we had a file where we could just record the fixes. Do you think we could easily arrange something like this?

**Comment by teixeirak** [comment]
What would be an easy way to record the data? Would it make sense to just edit the errors report doc?  (By the way, I'm home sick today, as opposed to being out in the field, but the others are all out there.)

**Comment by ValentineHerr** [comment]
I supposed editing the error report can work. We will look at the changes in the error report and manually make them in the excel file (faking a new download of data). The only thing is that the error report will be overwritten... but we can refer at the same commit to look back at the changes to make if they are not all fixed in the data in one go.

**Comment by teixeirak** [comment]
Hmmm... if we'd be manually making changes, I think it's easiert to just re-deploy the form via FastField. That doesn't take a huge amount of time, and then we don't  have to make any manual changes. Agreed?

**Comment by ValentineHerr** [comment]
yeah that is probably best

**Comment by teixeirak** [comment]
okay, thanks.

**Comment by teixeirak** [comment]
I'm re-opening this issue because the only way I can figure out to dispatch in FastFieldForms is now painfully slow. I previously wrote [these instructions](https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/doc/Protocols/editing%20records%20with%20errors.md) that use the legacy portal, but now the legacy portal appears to have completely disappeared. I can dispatch using the new system, but it takes several minutes at the "fill form" stage: 
<img width="995" alt="image" src="https://user-images.githubusercontent.com/6355854/202473331-a8ed7409-5185-4c49-b1e6-829c14a12b0e.png">

This is not a workable system. We're probably close to dropping FastField altogether, but in the meantime I wanted to check if @jess-shue , @djj4tree , or @mageeluke have any suggestions. If not, it may end up being fastest to just edit the files directly without re-deploying to fast field.

**Comment by jess-shue** [comment]
Hi @teixeirak,
  If there are any edits that don't require checking things in the field we can make those through the FastField Forms website - I can help with that if anything falls into that category. We had talked with them several times about this and I think the main issue comes down to the size of our data in the app.
   They have created these new 'Global Workflows'. I can look into setting something up. I think we (@djj4tree , @mageeluke, @teixeirak) should talk about the mortality surveys for next year as in theory SCBI will be using ArcGIS to collect census and mortality data.

**Comment by mageeluke** [comment]
Hi @teixeirak @jess-shue,

After some searching, I found the old portal through this link: https://portal.fastfieldforms.com/SubmissionActivity

Happy to discuss alternatives as well.

**Comment by jess-shue** [comment]
Thanks @mageeluke! 

@teixeirak I also built a new app - Field_Fixes_2022. You can choose the quadrat, see how many corrections there are, then enter a subform. That subform looks pretty much the same as what was used in the field but I added a 'Data Correction' line that shows the error listed in teh field_fix_error_file.

Hopefully, one of these two options will work!

**Comment by teixeirak** [comment]
Thanks, @mageeluke and @jess-shue ! It looks like using Field_Fixes_2022 (in conjunction with [require_field_fix_error_file.csv](https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/testthat/reports/requires_field_fix/require_field_fix_error_file.csv) to identify the error) will be the easiest, right?  I guess I wasted time dispatching quadrats with errors-- should have asked you sooner! :-) 

I looked at an example quad (102) and saw 4 stems (10013, 10021, 10134, and 10157), but I don't see the last of those  (10157) in [require_field_fix_error_file.csv](https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/testthat/reports/requires_field_fix/require_field_fix_error_file.csv). Why does that one appear?

**Comment by jess-shue** [comment]
@teixeirak I'm not sure, maybe I had an earlier version of the field_fix_error_file on my desktop. I'll make sure things are up-to-date and re-upload the data. I'll email you when complete.

**Comment by teixeirak** [comment]
@jess-shue has now updated FastField with a corrections file (thanks Jess!).

    Adding the corrections once they're submitted will require a different approach - you'll no longer be editing the original field form and so downloading all of the data and re-running the code as usual won't add the corrections. If that makes it too complicated and you were able to use Luke's link, maybe dispatching is still the right way to go...

@ValentineHerr , do you think it will be easy enough to work with this system? If not, we can try dispatching.

**Comment by ValentineHerr** [comment]
I am not sure I understand all the implications of this approach... I think you can just do what is easiest for the field crew and I'll figure out a way to work with it.

**Comment by ValentineHerr** [comment]
I think we can close this
